### ISSUE TITLE
Editing documents with OnlyOffice is not possible

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#10479]
## Describe the bug
Trying to edit a document (I honestly only tried .docx) in OnlyOffice is not possible with current ocis master. 

## Steps to reproduce
1. Create a .docx file in the web ui (or upload one)
2. Document gets opened in OnlyOffice (if you uploaded one: open it)
3. Try to edit the file

## Expected behavior
The various editor toolbars at the top are visible and the document can be edited.

## Actual behavior
The document can't be edited and the toolbars at the top are missing. Looks like read only mode.

## Additional context
I check that it's not a web issue by running the current ocis master with different web versions (current master, 11.0.0, 10.1.0). I also checked that it's not an OnlyOffice issue by running OnlyOffice 8.2.0 and 8.1.3. For 8.1.3 I know that it worked from a sprint demo 2,5 weeks ago. Good old git bisect between ocis-rolling:6.6.1 and current master might be a good way to find the faulty commit... unless the regression is in reva. 😅 
Web properly adds the `view_mode=write` query param to the `/app/open` url. That was my first assumption...

**Comment by micbar** [comment]
There has been a change today in ocis #10335

Please add `COLLABORATION_APP_PRODUCT=OnlyOffice` (upper or lowercase doesn't matter)

**Comment by kulmann** [comment]
Ok, thank you, I can confirm that "fix".
However, the PR doesn't even have a changelog item. How are admins supposed to find out what to do?

To close this issue here we should at least come up with a changelog with a prominent breaking change note. Changes in the dev docs would also be good - a prominent hint that starting with ocis 7.0.0 / ocis 6.7.0 if you want to use onlyoffice you need to set that env var to the collaboration service. Probably also something @mmattel wants to add to the admin docs.

**Comment by jvillafanez** [comment]
> The document can't be edited and the toolbars at the top are missing. Looks like read only mode.

I'm pretty sure this is a consequence of how the app URLs are handled differently between Collabora and OnlyOffice. The handling is covered in https://github.com/owncloud/ocis/blob/master/services/collaboration/pkg/service/grpc/v0/service.go#L187

Basically, despite we're connecting to an OnlyOffice instance, we're assuming it's Collabora (it's the default value), and the method to choose the right app url is different for Collabora. The result is that we use the view URL instead of the expected edit URL.

We probably should check how we can improve the upgrade scenario.
