### ISSUE TITLE
Default Content Security Policies

### ISSUE THREAD

**Issue by TommyTran732** [owncloud/ocis#10528]
It would be really great if the OCIS container is shipped with a default set of CSP policies. This will remove the need for sysadmins to write it at the reverse proxy level, and ensures that the CSP policies do not break OCIS with a future update.

**Comment by micbar** [comment]
@TommyTran732 This is part of ocis since version 6.0.0.

Per default, it uses this template https://github.com/owncloud/ocis/blob/master/services/proxy/pkg/config/csp.yaml

In our recommended docker compose example, we have a little magic there to adapt for the WebOffice embeds. https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_full/config/ocis/csp.yaml

Make sure, when you are using an external IdP like keycloak, to add it to the `connect-src` like https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_keycloak/config/ocis/csp.yaml#L9
