### ISSUE TITLE
[QA] Deleted user can upload files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1072]
Deployed ocis master 2020-12-11 13:30h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

* on the Web UI: log in as moss, create user testy, assign role User
* with a second browser session: log in as testy.
* while testy is logged in: user moss deletes user testy.
* from the second browser session: user testy uploads a file. BAD.

Expected behaviour: deleted users gets logged out at their first interaction. He should not be able to do anything anymore.

A deleted normal user can create shares. The share receiver sees a blank user name, or `{}`
A deleted admin user cannot create more users. Pfff

**Comment by kulmann** [comment]
On a go instance which runs from the command line with the single binary, the test user see error messages on any action. He doesn't get logged out - that would be ideal - but none of my actions from the web ui succeeded with the deleted user.

See for example this upload:
<img width="1616" alt="Screenshot 2020-12-11 at 18 09 24" src="https://user-images.githubusercontent.com/3532843/101933199-284e5c00-3bdc-11eb-8748-8e769a6ecf84.png">


Need to check if the traefik deployment example does anything different.

**Comment by kulmann** [comment]
Found the culprit: The deployment example has `PROXY_AUTOPROVISION_ACCOUNTS` set to `true`, while ocis master has it as `false` by default.

The issue is a tough one: when we have an external IdP we need to learn the users in our accounts service in order to assign them an internal uuid. At the same time we cache the `userinfo` for the current access token (during the access token lifetime). This means: when autoprovisioning to our accounts service is enabled, a deleted user gets recreated from the userinfo during the lifetime of the access token. This needs to be sorted out ASAP.

**Comment by kulmann** [comment]
A possible solution could be disallowing autoprovisioning on cache hits.

**Comment by jnweiger** [comment]
Confirmed fixed with a master 2020-12-14 15:00h installation.

**Comment by jnweiger** [comment]
fixed in rc8
