### ISSUE TITLE
[QA] Webupload fails when file gets overwritten with a shorter version

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1079]
Deployed ocis master 2020-12-11 13:30h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

* login as einstein
* start uploading a 25MB jpg file
* while the upload is in progress, overwrite the file with a shorter 24MB jpg file
* the upload continues, hangs at the end for a few minutes, then fails. BAD
![image](https://user-images.githubusercontent.com/1108546/101968687-a896b080-3c20-11eb-8174-2a33c309daab.png)

Expected behaviour: either the first or the second version should be uploaded correctly.

When we overwrite with a larger 26MB jpg instead, then the upload succeeds.
The original file is uploaded correctly.

**Comment by kulmann** [comment]
This should be solved in the web ui. We have an upload queue, so it would be easy to check if there is an item with the same path in the queue already and don't allow subsequent uploads until it is done in the queue.

More context: From a UX perspective it would also be good to allow cancelling uploads, but that's another story. We are currently investigating if [uppy](https://github.com/transloadit/uppy) could solve some of our issues.

**Comment by individual-it** [comment]
- [ ] ToDo for QA-team: add an UI test for this case

**Comment by dpakach** [comment]
Automated tests added in https://github.com/owncloud/web/pull/4553

**Comment by dpakach** [comment]
@jnweiger I could not reproduce this issue with latest git version of ocis, The upload stops as soon as the file is overwritten and fails in around 30s. The behavior is same for overwriting with larger and smaller file sizes. the error message is different this time from the one displayed originally in this issue,

![Screenshot from 2020-12-23 17-04-21](https://user-images.githubusercontent.com/19869344/102991386-30de5500-4541-11eb-9851-2c5db1257abb.png)

No files are created in the server since the upload itself fails, Do you think this is the correct behavior?

**Comment by ScharfViktor** [comment]
local server oCIS version 1.11.0
re-tested. works correctly, I propose to close

https://user-images.githubusercontent.com/84779829/132225449-23b39e2c-5ed0-4bb8-8c59-b53fbe142612.mov
