### ISSUE TITLE
No robots.txt available

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1314]

**Comment by jvillafanez** [comment]
https://github.com/owncloud/web/pull/5762 should fix the issue.
As far as I know, it will require a new web release and an adjustment in the ocis makefile to bring those assets.

**Comment by jvillafanez** [comment]
should we close this or wait until the next web release?

**Comment by pascalwengerter** [comment]
> should we close this or wait until the next web release?

Let's close this upon merging the next web release here:)

**Comment by pascalwengerter** [comment]
Fixed since ownCloud Web 4.2.0 (2021-09-14) thanks to @jvillafanez

**Comment by SagarGi** [comment]
This issue seems to have been closed but is still in expected to failure: So reopening.

https://github.com/owncloud/ocis/blob/176dd321b1f8b85a45440119541cc3be17fe0125/tests/acceptance/expected-failures-API-on-OCIS-storage.md?plain=1#L829-L831

TODO QA-team
- [ ] review tests linked to this issue
- [ ] remove them from expected to fail if they pass or create another issue if necessary
