### ISSUE TITLE
Find a way to read and clear the logs from the acceptance tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1322]

**Comment by refs** [comment]
ping @individual-it , still relevant?

**Comment by individual-it** [comment]
yes would be helpful to be able to check the logs from the tests to be able to catch bugs that cause "only" log-outputs and no other easy-to-observe behaviour

**Comment by phil-davis** [comment]
And to be able to test logging features, not just bugs. For example, a test scenario (or whole pipeline) might set the logging level to some more verbose level, make some relevant API calls, then confirm that the log has the expected entries.

**Comment by refs** [comment]
Currently it is possible to output the log of each individual service to their own log file. If this is desirable for CI and we're okay with generating artifacts we can go down this road. Would that be helpful?

**Comment by phil-davis** [comment]
Note: we added code in the API acceptance tests so that they send an `X-Request-Id` header with each API  request. Those can be logged by the server when it logs a problem. That helps to be able to match up the test step, API request and error log entry when running tests.

I realize this issue is different - we want to be able to clear the logs and inspect the logs from the test runner, so that we can test the error logging behavior.

**Comment by phil-davis** [comment]
@individual-it what to do about this?
And is this about API tests (local ones, and/or ones from core), and/or web UI tests?

core API tests, that run against different systems-under-test (oC10, oCIS, reva) would have to understand where/how to see log output of the specific system-under-test. Because the backend "internal" logging of a system-under-test can be implemented however the system-under-test wants to do it.

**Comment by micbar** [comment]
@individual-it still relevant?
