### ISSUE TITLE
No way to set default folder for received shares

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1327]

**Comment by phil-davis** [comment]
> For now we should assume that the shares are always arriving in the "/Shared" folder and are not movable.

In reva and OCIS the folder is called `/Shares`

**Comment by phil-davis** [comment]
Some time ago we sorted out the acceptance test suites so that there are scenarios that test sharing with the share_folder set to `Shares`. When running against oC10, the `share_folder` in the config gets explicitly set to `Shares`. When running against oCIS, that is already the default, and the step that "sets the config" does nothing.

There is another set of sharing scenarios that has the oC10 default - `share_folder` is not set, and received shares appear in the root of the receiving user's file system. Those scenarios are only run with CI against oC10. They are not applicable to oCIS.

At some time, someone will need to decide if the hard-coded `Shares` folder in oCIS should have a configurable name, or...

**Comment by pmaier1** [comment]
> In reva and OCIS the folder is called /Shares

Exactly. And there are no plans for now to make this configurable. Please adjust tests and remove from expected failures.

**Comment by phil-davis** [comment]
We have already adjusted the test suite so that all the sharing tests are done with a `Shares` folder for oCIS CI.
There are other tests that check the default oC10 sharing behavior - the received shares appear in the root of the receiver's file system. Those are all tagged `notToImplementOnOcis`

There should not be any tests in expected-failures related to this. @dpakach please get someone to double-check.

**Comment by pmaier1** [comment]
I found this from https://github.com/owncloud/ocis/blob/master/tests/acceptance/expected-failures-API-on-OCIS-storage.md

**Comment by individual-it** [comment]
tests are marked `@notToImplementOnOCIS` in https://github.com/owncloud/core/pull/39117 so closing this issue
