### ISSUE TITLE
Range Header is not obeyed when downloading a file

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1346]
found when starting to run API tests with OCIS

try to download only a range of a file, e.g.: `curl http://localhost:9140/remote.php/webdav/home/welcome.txt -u einstein:relativity -H "Range: bytes=51-77"`

### Expected behaviour:
only a range of the file should be downloaded

### Actual behaviour:
the complete file is downloaded

**Comment by butonic** [comment]
tracked in reva as https://github.com/cs3org/reva/issues/1395

**Comment by phil-davis** [comment]
Note: we added tests in https://github.com/owncloud/core/pull/38247 to check various combinations of range request.
In the RFC it is acceptable for a server to reply to a range request with either status `206` and the range(s) requested (e.g. a multi-part range request) or to reply with status `200` and send the whole file. For example, if the server does not even support range requests it is free to "ignore" the requested ranges and just deliver the whole file. Also the server is free to decide its own "optimization" of the reply - for example, if the request is for a part of a small file then the server can choose to just send the whole file, rather than "bother" to send just the exact requested range.

We made the tests cope with that allowed variation.
