### ISSUE TITLE
Panic when downloading

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#1351]
When downloading via phoenix, we get 502 in CERN's setup. 
Logs: https://gist.github.com/ishank011/2ec204692a6cc1092db68b743857fdf6

**Comment by refs** [comment]
@ishank011 could you provide a bit more input? 👯 I suspect that accounts middleware is acting funny. It would be helpful if you could post the phoenix request since such middleware can be bypassed, and I would like to see what the implications are.

**Comment by refs** [comment]
I tried killing the usual suspect, the ocis store, but I'm not reproducing the issue that way. I think the smoking gun is the accounts middleware, as your logs show

**Comment by ishank011** [comment]
@refs Clicking on a file first sends a HEAD request which returns successfully
```
Request URL: https://cbox-spare-02.cern.ch:9200/remote.php/webdav/hello.txt
Request Method: HEAD
Status Code: 200 OK
Remote Address: 127.0.0.1:12345
Referrer Policy: strict-origin-when-cross-origin
```
followed by one to the endpoint, which returns a 502
```
Request URL: https://cbox-spare-02.cern.ch:9200/ocs/v1.php/cloud/user/signing-key
Request Method: GET
Status Code: 502 Bad Gateway
Remote Address: 127.0.0.1:12345
Referrer Policy: strict-origin-when-cross-origin
```
The complete logs are here https://gist.github.com/ishank011/2ec204692a6cc1092db68b743857fdf6
I don't see any others.

Also, all these background requests `remote.php/dav/files/iarora/abc.txt?a=1&c=424293cbda57c4ed5931b8a011f7ea59&preview=1&scalingup=0` return a 500, and I see that these return a 404 at https://ocis.owncloud.works/.

One more thing. How do we disable tus from phoenix?

**Comment by ishank011** [comment]
As @butonic mentioned, this should be handled by reva but apparently, it is somehow being redirected to ocis.

**Comment by ishank011** [comment]
But looking at https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocs/handlers/cloud/user/user.go, this won't be the issue, as it should always return 200

**Comment by ishank011** [comment]
`u.Opaque` is probably nil here https://github.com/owncloud/ocis/blob/master/ocis-pkg/middleware/account.go#L70

**Comment by ishank011** [comment]
Yep. `opaque:<map:<key:\"gid\" value:<decoder:\"plain\" value:\"2763\" > > map:<key:\"uid\" value:<decoder:\"plain\" value:\"125677\" > > >`

**Comment by butonic** [comment]
@ishank011 regarding TUS: as long as TUS headers are present ocis web will use them. https://github.com/owncloud/owncloud-sdk/pull/461

Which means that on EOS which does not support TUS the ocdav handler should not announce them in PROPFIND headers. which is currently hardcodet to true: https://github.com/cs3org/reva/blob/a7bf52ba4cf145baeb4b72d5dca485c731d5c1a7/internal/http/services/owncloud/ocdav/propfind.go#L192-L197

We could return capabilities like this in aResourceInfo Opaque propery ... because it might change from file to file ...

**Comment by ishank011** [comment]
@butonic oh okay. I added a change which fixes the capabilities response in ocs https://github.com/cs3org/reva/pull/1331. Can we somehow propagate that to ocdav? Otherwise, I'll add the opaque property to EOS resources

**Comment by butonic** [comment]
forget the capabilities endpoint. it has to die for anything related to files. having a single endpoint does not make sense because the capabilities might change with every tree, maybe even for every folder and file.

TUS ist a good example. It really is specific to the folder and we should announce it in the PROPFIND / HEAD requests using the proper headers. So I strongly vote for opaque properties.

**Comment by ishank011** [comment]
Cool, I'll make the change. Thanks for looking into this!

**Comment by butonic** [comment]
@ishank011 we could add tus support to https://cs3org.github.io/cs3apis/#cs3.storage.registry.v1beta1.ProviderInfo.Features
