### ISSUE TITLE
Prefix env vars

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#1352]
Currently each extension is configured with its own set of config vars, see:

- [thumbnails](https://github.com/owncloud/ocis/blob/master/thumbnails/pkg/flagset/flagset.go#L58)
- [accounts](https://github.com/owncloud/ocis/blob/master/accounts/pkg/flagset/flagset.go#L84)
- [proxy](https://github.com/owncloud/ocis/blob/master/proxy/pkg/flagset/flagset.go#L55)

Do we want to add a prefix to any OCIS related environment variables such as, for example, `OCIS_` in order to "bundle" OCIS configuration parameters together within an environment?

If we do so, it would be nice for it not to be a hard change and provide backwards compatibility with existing running environments. The outcome of this discussion should be a small list with Pros and Cons. An entry point is [Viper's SetEnvPrefix](https://github.com/spf13/viper#working-with-environment-variables)

**Comment by butonic** [comment]
we started with env vars prefivey by the service name, eg `PROXY_...`, `GLAUTH_...` but then things like <`service>_OIDC_ISSUER` were duplicated, which made setting up the zoo of services error prone because you would forget to set it for one of the services ... so now some of these can be set via two env vars: a service specific one that takes precedence and one that targets a single service. `OIDC_ISSUER` is one of them. `OCIS_URL` is another one ... I don't know if we also have others eg for `LDAP_...`, yet.

**Comment by butonic** [comment]
we started with env vars prefivey by the service name, eg `PROXY_...`, `GLAUTH_...` but then things like <`service>_OIDC_ISSUER` were duplicated, which made setting up the zoo of services error prone because you would forget to set it for one of the services ... so now some of these can be set via two env vars: a service specific one that takes precedence and one that targets a single service. `OIDC_ISSUER` is one of them. `OCIS_URL` is another one ... I don't know if we also have others eg for `LDAP_...`, yet.

**Comment by xoxys** [comment]
Pros:

- good overview/easy search in a dumped environment (namespacing)

Cons:

- may result in long variable names (but technically we should never reach the limitation https://devblogs.microsoft.com/oldnewthing/20100203-00/?p=15083)

**Comment by xoxys** [comment]
Unstale?

**Comment by pascalwengerter** [comment]
Can maybe be combined with #97?

**Comment by xoxys** [comment]
Again? Can we consolidate it now and close this issue or add a label to it to prevent staling?

**Comment by phil-davis** [comment]
IMO the Technical-Debt label prevents the stale bot from closing the issue.

**Comment by refs** [comment]
> IMO the Technical-Debt label prevents the stale bot from closing the issue.

[yes](https://github.com/owncloud/ocis/blob/7b1a7b20f179babce1a7ec5d4a644fc7a066fe60/.github/stale.yml#L8-L10)

**Comment by kobergj** [comment]
Decided to do the opposite. Closing this issue.
