### ISSUE TITLE
extract ocs from reva and wrap as ocis-extension

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#1422]

**Comment by phil-davis** [comment]
@butonic this is an old issue that was transferred from the archived `ocis-ocs` repo a few weeks ago.
Please close if no longer relevant.

**Comment by pascalwengerter** [comment]
@butonic or @micbar could you provide some feedback on this? :)

**Comment by pascalwengerter** [comment]
> @butonic or @micbar could you provide some feedback on this? :)

Would love to get some feedback if this means the ownCloud storage driver or ownCloud storage service (which one could expect to live in https://github.com/owncloud/ocis/tree/master/ocs)

**Comment by wkloucek** [comment]
Some functionality lives in REVA OCS and some in oCIS OCS... These should ideally be merged somewhere. Or they will diverge even further...

- oCIS OCS: https://github.com/owncloud/ocis/blob/0837a36ad83d7654d66623041a8d5ca7a45c573c/ocs/pkg/service/v0/service.go#L77-L135
- REVA OCS: https://github.com/cs3org/reva/blob/0cb3bcbad5456611db1547fc4579cf97e1dfee6d/internal/http/services/owncloud/ocs/ocs.go#L89-L143

As of today we already do weird things because of the two implementations and their respective limitations / bugs, eg in the parallel deployment (https://github.com/owncloud/ocis/blob/0837a36ad83d7654d66623041a8d5ca7a45c573c/deployments/examples/oc10_ocis_parallel/config/ocis/proxy.json#L23-L31)

This will also pop up when getting rid of the accounts service, since the oCIS OCS is using it.

**Comment by wkloucek** [comment]
Only the signing-key is left in the oCIS ocs implementation:

https://github.com/owncloud/ocis/blob/master/extensions/proxy/pkg/config/defaults/defaultconfig.go#L86-L90

Therefore highly related to https://github.com/owncloud/ocis/issues/3913

**Comment by rhafer** [comment]
Most of ocs was moved to reva meanwhile (opposite to what this issue was originally about). The only missing bit is the signing-key related stuff. So I am closing this in favor of #3913
