### ISSUE TITLE
It is not possible the edit my user preferences using GUI

### ISSUE THREAD

**Issue by erwinpalma** [owncloud/ocis#1493]
### Server configuration
**Operating system**:
Mac OS X

**ownCloud version:** 
 ocis version 1.1.0-rc1

**As a normal user**: I would like to update/change the following information but it is not possible
- Update my Avatar.
- Change/Edit my name
- change/edit my email.

Log as User

1. Los gas User
2. **Click** on the **username --> Profile** to open the "profile settings page"
3. **Click** on the **Edit button**.

![useraccount001](https://user-images.githubusercontent.com/30660343/105840756-d1f27c80-5fd3-11eb-8a66-38055990898a.png)

4. The only option to configure is the Language settings and the **settings and account links** are disabled.

![useraccount002](https://user-images.githubusercontent.com/30660343/105841623-33ffb180-5fd5-11eb-9992-af53fa3c20ac.png)

## Describe the solution you'd like

Add the HTML elements to edit/update/add/delete the user settings.

**Comment by erwinpalma** [comment]
FYI @micbar :)

**Comment by micbar** [comment]
Language setting is currently the only implemented setting in ocis.

The user settings of the oc10 backend need to be set within the "Classic UI". There is a link in the profile dropdown menu.

**Comment by erwinpalma** [comment]
> Language setting is currently the only implemented setting in ocis.
> 
> The user settings of the oc10 backend need to be set within the "Classic UI". There is a link in the profile dropdown menu.

Unfortunately, I was not able to find the option.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/30660343/106003364-6d5a1f00-60b2-11eb-9158-a9907907c518.png">

**Comment by kulmann** [comment]
@erwinpalma ownCloud Web can run on top of the oCIS backend or the oc10 backend. On top of oc10 the account can be configured in the classic frontend. On top of oCIS the account management is part of the identity provider. We're still trying to figure out a good way to still have account preferences available in our frontend. But being really blunt about it, this didn't have the highest priority.

**Comment by erwinpalma** [comment]
I do not want to be rude, but talking as regular user, if I can't adjust my preferences, then the product is not usable ;(

- how can I adjust my email account?
- how can I change my name if I made a mistake?

I know it is not the priority, but improve the user experience will increase the acceptance of the users.

(just a point of view)

**Comment by refs** [comment]
> how can I adjust my email account?

As @kulmann mentioned "the account management is part of the identity provider" The issue here is that we currently haven't "wired" the identity provider within the settings service. Let me explain. We have a few ways of providing accounts:

- file account manager (it uses system files to store user information)
- LDAP, for which we use GLAuth.

For the file account manager we can do any CRUD operation as it equates to operations to a database (alas "less efficient"). With LDAP it's another story, since GLAuth has no write functionality implemented. It is essentially read only, so things are a bit more twisted on that end.

We have an ADR in place to tackle exactly this issue that you can have a look [here](https://github.com/owncloud/ocis/blob/master/docs/ocis/adr/0005-cs3-api-account-management.md), we only have to follow through and schedule it for development.

There are many missing functionalities regarding oCIS, this is one of them. We were prioritizing EFSS at the moment.

**Comment by micbar** [comment]
Language settings and "show hidden files" settings are implemented today. Closing here because all other features are part of the roadmap.
