### ISSUE TITLE
Discussion: Squashing vs. Rebasing

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#150]
Let's have a common place to agree on commits to the master across all extensions.

**Comment by labkode** [comment]
@refs Squashing :)

**Comment by kulmann** [comment]
Squashing would make sense if the commit history was our content source for the changelog. But since we made the decision to have user/admin targeted changelogs that are handcrafted in changelog items, there is no need to have a "1 commit = 1 feature" style of commit history in master. Just as an example, bisecting would become more useful if we had a fine grained commit history instead of bigger, squashed commits.

**Comment by IljaN** [comment]
https://dhwthompson.com/2019/my-favourite-git-commit
