### ISSUE TITLE
Name of binary in release tarball should be "ocis" ?

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#152]
The binary is currently named "ocis-1.0.0-beta1-linux-amd64". Imho it should be "ocis". Not sure about best-practices but it seems un-intuitive. 

If the full version string is required inside the tarball a directory "ocis-1.0.0-beta1-linux-amd64" could be created at the root of the tar which contains the "ocis" executable.

**Comment by wkloucek** [comment]
Is still the case for https://download.owncloud.com/ocis/ocis/1.0.0/ and GitHub releases. I don't see another way for doing this since we deliver binaries for multiple platforms.

Is it about getting rid the version in the filename since it seems redundant if we have it already in the folder name / GitHub release path?

**Comment by refs** [comment]
Why not folders with the platform? Like in https://download.owncloud.com/desktop/ownCloud/stable/2.7/
