### ISSUE TITLE
Confirmation Message after add/delete/modify an account

### ISSUE THREAD

**Issue by erwinpalma** [owncloud/ocis#1604]
## Is your feature request related to a problem? Please describe.

After add/delete/modify a user I don't get any confirmation message

for example: run the command 

`epalma@Cesars-MacBook-Pro:~/src/ocis$./ocis accounts add --username demo02 --mail none02@none.com --password p123p123 --description  "user demo 02" --enabled
epalma@Cesars-MacBook-Pro:~/src/ocis$
`

## Describe the solution you'd like
I recommend a message saying something like this:

The user "demo2" has been added/modified/removed succesfully

**Comment by refs** [comment]
@erwinpalma where would you like to see the message displayed? Within the UI or as an API response? Since that is a cURL command I would assume you'd like to see some sort of confirmation via a message the API returns in the response body that cURL could display, but we actually signal this using HTTP (or OCS) status codes.

Would it still be helpful for you to receive such response from the API?

**Comment by IljaN** [comment]
The best practices for cli tools on UNIX/Linux is to not display any messages if the operation was successful.  (mkdir, chmod, useradd etc.)
