### ISSUE TITLE
Translate OC 10 paths to OCIS

### ISSUE THREAD

**Issue by labkode** [owncloud/ocis#1876]
As a user I had bookmarked certain paths.
When migrating to OCIS these paths cease to work, disrupting my work and my colleagues.
This is specially painful for public links.

This is a non-exhaustive list of the paths that need translation:
* `index.php/s/<token>` (public links)
* `index.php/f/<fileid>`(private links)
* `apps/files/?dir=/Documents&fileid=32`

Where to implement? 
In the reva ocs service

Implement the redirect to the new format https://owncloud.dev/ocis/adr/0011-global-url-format/#mixed-global-urls

## Acceptance Criteria

- [ ] accept adr 0011
- [ ] all three url formats should redirect to the new url format
- [ ] web changes are out of scope 
- [ ] API acceptance test, query the old urls, check if it returns the redirects

**Comment by butonic** [comment]
we need examples for `fileid`

The logic in oc 10 is that `fileid` takes precedence if it is present:
- the resource will always be looked up by `fileid` 
- if `fileid` is not given `dir` is evaluated
- if both are given `dir` is ignored ... might be confusing to end users

in oc10 we have no storageid prefix in the fileid. is that the case in cernbox?

**Comment by refs** [comment]
findings so far:

regarding the public links, the bookmarked ones should work yet they don't because of what I suspect is vue's mode that defaults to `hash` therefore it adds an `#` to the URL. [sauce.](https://router.vuejs.org/api/#mode)

For that case I'd dig into changing to `history` mode that uses hew browser api's but it might be a case of "there be dragons".

For the `fileid` case I have a question:

- IIRC `fileid` in OC10 is an auto-incremented integer value, is that right?
- if that is the case, we cannot link an existing `fileid` from OC10 to one in oCIS as both ids differ.
  - does that mean we have to keep a reference to the old id (OC10) and store it as part of the file metadata?

I'd like to cross-check those assumptions before moving on with this ticket. /cc @butonic

**Comment by refs** [comment]
Essentially we want to:

- provide support for `fileid`
