### ISSUE TITLE
when sharer renames the shared resource, sharee get the updated name

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2256]
## Describe the bug

Sharee gets the updated resource name if the sharer renames the resource after sharing.

## Steps to reproduce

1. create two users `uu1` and `uu2`
2. create a folder `simple` using `uu1`
3. share `simple` folder with user `uu2` using user `uu1`
4. rename folder `simple` to `simple-renamed` using user `uu1`
5. login as user `uu2`
6. list `shared-with-me` shares

## Expected behavior
Using oc10 backend:
- `simple` folder should be present with shareowner `uu1`

## Actual behavior
- `simple-renamed` folder is present

> If this is the expected behavior please close the issue

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

with either storage backend

```console
OCIS_VERSION=git
BRANCH=latest
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

## Additional context
Test is covered [here](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIRenameFiles/renameFiles.feature#L227)

**Comment by phil-davis** [comment]
@kiranparajuli589 If `uu2` accepts the share, and then `uu1` renames the shared folder, what happens?

**Comment by kiranparajuli589** [comment]
> @kiranparajuli589 If `uu2` accepts the share, and then `uu1` renames the shared folder, what happens?

the issue is same after approval too @phil-davis

**Comment by phil-davis** [comment]
"somebody" needs to say what is the expected behavior for this sort of thing.

My example is:
- Alice creates a folder "Finannce" (with a typo)
- Alice shares "Finannce" with Brian (or a group...)
- Alice notices the typo in "Finannce" and renames the folder to "Finance"

For Brian, if he has not renamed the folder himself, then it seems reasonable that Brian "sees" the typo-fix change done by Alice.
The behavior of OCIS seems like "a reasonable thing".

In oC10, Brian still sees the typo. To "correct" the typo, Alice has to delete the share and create it again.

What should be the requirement?

**Comment by ScharfViktor** [comment]
no longer relevant. Same issue was closed https://github.com/owncloud/ocis/issues/6376
