### ISSUE TITLE
User personal settings page

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#2333]
For many apps, we need a page where the user can specify some personal settings.

Some examples:
- mail notification settings
- whether to automatically accept incoming local shares
- oauth2 app list
- session management
- setting avatar

I think not all of them would apply to Phoenix, but for those that do, we need a place to manage this.

For now the most obvious place would be under the "Account" page, add these all as sections.
This would also require a list of quick links to be able to jump to the sections (priority depends how many settings we'll have at first)

A less obvious place would be to display those settings closer to the feature. For example sharing settings would need to appear somewhere in the files app.

**Comment by wkloucek** [comment]
@kulmann @tbsbdr is this still valid? What needs to be done?

**Comment by pascalwengerter** [comment]
@wkloucek @kulmann once https://github.com/owncloud/ocis/pull/5463 is completed this can be moved to the `web`?

**Comment by kulmann** [comment]
I think meanwhile the scope of the issue is too broad and very much with oc10 in mind. As we're progressing with oCIS notification settings actually will happen in the next couple of weeks (issue in preparation, not yet on github), oauth2 app list and session management are not that relevant atm, ...

For the time being I'll close this issue and we'll open new ones in the `web` repo when the topics come up respectively.
