### ISSUE TITLE
Open Policy Agent (OPA) for ocis permissions / authorization ?

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#2456]
OCIS is supposed to provide a flexible way to assign and manage permissions based on Roles. It seems that OPA https://www.openpolicyagent.org/ is providing a framework that helps implementing systems like this. It provides a DSL for defining policy (called rego) and can be intergrated as an additional service or (go-)library into the code. Using some existing framework seems to be like a good choice (instead of inventing something new here). I know OPA has already been evaluated for other purposes in OCIS but has it been considered for the permissions and authorization features in OCIS?

cc @refs @micbar @butonic

**Comment by butonic** [comment]
cc @fschade

**Comment by refs** [comment]
It is true that this fits the bill for our use case. We still need a layer of persistence elsewhere that we can use as data source for write operations (since I doubt OPA writes end up in the Rego file).

At its core permissions and permissions enforcement is ultimately a boolean operation: allowed / not allowed, and at the core of OPA it is this very same question. Since the current roles and permissions on oCIS is not enforced in many places I think having a POC running with OPA should not be a huge task, especially knowing about the framework ourselves having worked on the [licenses WIP PR](https://github.com/owncloud/ocis/pull/2236).

It is a drawback and a bit of a sunken cost paradox. Should we stick to the current model we have (settings + roles) and document it entirely and check again it fits our use case with extension developers being able to define their own roles, or should we redesign it?

Another concept mix-up is the fact that the cs3api are also [aware of roles](https://cs3org.github.io/cs3apis/#cs3.auth.provider.v1beta1.Role) just on a different layer.

**Comment by rhafer** [comment]
I think this can be closed. Doesn't help to have this idea sitting around another 3 years ;-)
