### ISSUE TITLE
[Question] Add capability for app provider?

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#2482]
## Describe the solution you'd like
I suggest adding a capability for app provider since oCIS supports that feature and OC10 (most likely) never will.

## Describe alternatives you've considered
The wrapper for external apps will most likely be enabled via the config.json in `web`, but the request to fetch the list of provided apps should perhaps only happen if capabilities allow for it.

**Comment by pascalwengerter** [comment]
@wkloucek @micbar @kulmann opinions? Should be done rather quickly :)

**Comment by kulmann** [comment]
Like you said, adding the `app provider` application to the web `config.json` is probably the easiest on/off switch for the app. Since the app provider backend service is not part of oCIS by default (at least as far as I know now) it would be nice to have a reliable way to know if the backend service is available or not. One dead simple way would be to just make a request to the endpoint you mentioned - if it fails we know that the service is not reachable (for whatever reasons, not started, downtime, etc). I'd prefer a more gentle way to announce it. The capabilities are the closest we have as of now, so I'm in favor of adding such a capability.

There was another idea some time ago, which was basically to have an endpoint for listing available ocis extensions/services. From what I know we could add such a list to the capabilities endpoint as well (like `capabilities.services`). However, that was not discussed further and doesn't exist as of now, so not relevant for the issue that you described.

**Comment by micbar** [comment]
Adding a capability in ocis is quite simple.

**Comment by wkloucek** [comment]
Will be tackled in https://github.com/cs3org/reva/pull/2088
