### ISSUE TITLE
Skip demo user generation

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2484]
## Is your feature request related to a problem? Please describe.
As an oCIS admin I want to run an instance without default users (einstein, marie, ...).
As an oCIS admin I want to easily setup oCIS without demo users.

## Describe the solution you'd like
There is a feature flag to skip / enable the demo user generation.

## Describe alternatives you've considered
- Deleting them manually like described in https://owncloud.dev/ocis/deployment/#delete-demo-users. But then I need to do this at every oCIS restart

CC @C0rby

**Comment by jvillafanez** [comment]
https://github.com/owncloud/ocis/pull/2495 should fix this.
In addition to the sysusers, which are needed according to the docs, I've also left the admin user so the actual admin can enter the platform.

I'm still a bit worried with the group generated due to the additional data we're sending with the "users" group, because the members are missing if the demo users aren't being generated. In addition, the "admin" wasn't present as part of the "users" group.

**Comment by wkloucek** [comment]
Needs documentation and can than be closed.
