### ISSUE TITLE
Preview of text file with UTF content does not render correctly

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#2570]
## Steps to reproduce

1. Create a text file with UTF characters in it (for example Devanagari font - Hindi/Nepali)
2. View the generated preview

## Expected behavior
The UTF characters are rendered and readable in preview

## Setup

See acceptance test scenario apiWebdavPreviews/previews.feature:208

**Comment by phil-davis** [comment]
Note: this was made to work in core oC10 PR https://github.com/owncloud/core/pull/39272

**Comment by phil-davis** [comment]
@kiranparajuli589 please get a preview in oCIS of some Devanari text and look and see if there is any readable Devanagari or if it is all scrambled.

**Comment by kiranparajuli589** [comment]
- for a file containing Devanagari only, the preview response shows boxes `[]` like:
 > ![devanagari-only](https://user-images.githubusercontent.com/39373750/135805449-b8115236-3564-4471-8627-80ab44c914b1.jpg)
- for a file containing mixed content too, the Devanagari texts turn into boxes.
 > ![mixed-text](https://user-images.githubusercontent.com/39373750/135805553-e6a22cee-0b75-4d78-90a4-295c5acf5143.jpg)
@phil-davis

**Comment by phil-davis** [comment]
Good to know. oCIS does not have the code to generate text previews of "different" character sets.

**Comment by saw-jan** [comment]
By default, ocis cannot generate accurate preview of unicode characters (default font is `Go Regular`). oCIS needs a set of fonts that supports unicode in order to generate the preview correctly.
And the font file can be provided using `THUMBNAILS_TXT_FONTMAP_FILE`. See [docs](https://doc.owncloud.com/ocis/next/deployment/services/s-list/thumbnails.html)

PR https://github.com/owncloud/ocis/pull/6931 tries to setup the correct configuration for preview tests
