### ISSUE TITLE
Investigate Propfind deep benchmark

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#2687]
## Description

We have a slight performance drop (~25%) between ocis 1.13 and ocis 1.14.

See #2671 

Investigation is needed.

**Comment by micbar** [comment]
Still open

**Comment by micbar** [comment]
still needs investigation

**Comment by micbar** [comment]
still needs investigation

**Comment by butonic** [comment]
this is getting worse. AFAICT cdperf uses the legacy `/dav/files/{username}` endpoint. For that the ocdav service acts as a client that has to query every storage space a user has access to to determine the most recent etag to present for the root. First the code lists all storage spaces the user has access to, then it has to do a stat request to fill the etag and mtime. by requesting the [new root_info property](https://github.com/cs3org/cs3apis/pull/173/files#diff-b91600c359c2e479b2dbc31ff8dd5bd52bfaa48dc70c33a0de121215ff0c030eR465) we could get rid of the additional stat request.

Furthermore, the ocdav service should cache share spaces for recipients, because they don't need to immediately see changes when using the legacy endpoint.
