### ISSUE TITLE
Client reconnect can cause user mismatch

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#269]
Re-connecting client sessions can lead to confusion which user name to use.

I have both, Einstein and Marie setup in one client:
![image](https://user-images.githubusercontent.com/1108546/81660574-39af6a00-943b-11ea-9a83-f3b8c9732a89.png)

when re-connecting them, a web-browser opnes with an IDP dialog for each connection. OK
The expected username is not visible in these dialogs, the user has to guess, which is which.

![image](https://user-images.githubusercontent.com/1108546/81662622-2356dd80-943e-11ea-8140-0cb60fc4ee84.png)

Both connections start the browser almost simultaneously, the user has to guess, which user to enter where. If he guesses wrong, the authentication fails:
![image](https://user-images.githubusercontent.com/1108546/81660309-dcb3b400-943a-11ea-9cef-ad59ab5d8409.png)

**Comment by michaelstingl** [comment]
> Re-connecting client sessions

@jnweiger Why did the client loose the login? Triggered by you manually? Or another/new issue?

**Comment by jnweiger** [comment]
That was a restart on the next day. Client quit, server quit. Server start, client start. The client still remembered the sync connetions of Einstein and Curie. It was not an exactly clean restart, too many cookies and stored users in the browsers. So it took me a while to get it going. 
If needed, I can try to recreate a more complete picture from scratch.

**Comment by refs** [comment]
@jnweiger still relevant? :)

**Comment by ScharfViktor** [comment]
The problem is reproducible. But, in my opinion, it is not necessary. If you enter the data of another user, you get a message with a recommendation to choose the right user. Also in the client for each user there is a button "Re-open Browser" (You can't go wrong here) 
<img width="806" alt="Screenshot 2021-08-30 at 14 37 24" src="https://user-images.githubusercontent.com/84779829/131340158-a9fc05c1-dc86-4412-8446-3c0632b05a61.png">
I propose to close the task. what do you say?
