### ISSUE TITLE
add spaces WebDAV URL as a third variant for WebDAV path

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#2854]
Part of #2808

currently we use `old` and the `new` WebDAV path in the tests
old: `remote.php/webdav`
new: `remote.php/dav/files/<username>`

now we also need to run the tests with the new spaces concept.
The "private" space should react the same as the other WebDAV urls `/dav/spaces/<uuid>/`

The Example tables of the webdav related tests need to get an extra line. e.g.
```
  Scenario Outline: upload a file and check download content
    Given using <dav_version> DAV path
    When user "Alice" uploads file with content "uploaded content" to <file_name> using the WebDAV API
    Then the content of file <file_name> for user "Alice" should be "uploaded content"
    Examples:
      | dav_version | file_name      |
      | old         | "C++ file.cpp" |
      | old         | "file #2.txt"  |
      | new         | "C++ file.cpp" |
      | new         | "file #2.txt"  |

    @skipOnOcV10
    Examples:
      | spaces      | "C++ file.cpp" |
      | spaces      | "file #2.txt"  |

**Comment by Talank** [comment]
@amrita-shrestha is looking into this issue

**Comment by kiranparajuli589** [comment]
### TODO:
**Note:** Please create a separate issue when you're taking one of the suites from above todo, link that issue with the correct suite and properly (check/uncheck) boxes after that. Also, mark your in-progress suites, so that others will not start working on that.

- [ ] apiAuth
- [ ] apiAuthOcs
- [ ] apiAuthWebDav
- [ ] apiCapabilities
- [ ] apiComments
- [ ] apiFavorites
- [ ] apiFederationToRoot1
- [ ] apiFederationToRoot2
- [ ] apiFederationToShares1
- [ ] apiFederationToShares2
- [ ] apiMain
- [ ] apiProvisioningGroups-v1
- [ ] apiProvisioningGroups-v2
- [ ] apiProvisioning-v1
- [ ] apiProvisioning-v2
- [ ] apiShareCreateSpecialToRoot1
- [ ] apiShareCreateSpecialToRoot2
- [ ] apiShareCreateSpecialToShares1
- [ ] apiShareCreateSpecialToShares2
- [ ] apiSharees
- [ ] apiShareManagementBasicToRoot
- [ ] apiShareManagementBasicToShares
- [ ] apiShareManagementToRoot
- [ ] apiShareManagementToShares
- [ ] apiShareOperationsToRoot1
- [ ] apiShareOperationsToRoot2
- [ ] apiShareOperationsToShares1
- [ ] apiShareOperationsToShares2
- [ ] apiSharePublicLink1
- [ ] apiSharePublicLink2
- [ ] apiShareReshareToRoot1
- [ ] apiShareReshareToRoot2
- [ ] apiShareReshareToRoot3
- [ ] apiShareReshareToShares1
- [ ] apiShareReshareToShares2
- [ ] apiShareReshareToShares3
- [ ] apiShareUpdateToRoot
- [ ] apiShareUpdateToShares
- [ ] apiSharingNotificationsToRoot
- [ ] apiSharingNotificationsToShares
- [ ] apiTags
- [ ] apiTranslation
- [ ] apiTrashbin
- [ ] apiTrashbinRestore
- [ ] apiVersions
- [ ] apiWebdavEtagPropagation1
- [ ] apiWebdavEtagPropagation2
- [ ] apiWebdavLocks
- [ ] apiWebdavLocks2
- [ ] apiWebdavLocks3
- [ ] apiWebdavLocksUnlock
- [ ] apiWebdavMove1
- [ ] apiWebdavMove2
- [ ] apiWebdavOperations
- [ ] apiWebdavPreviews
- [ ] apiWebdavProperties1
- [ ] apiWebdavProperties2
- [ ] apiWebdavUpload1
- [ ] apiWebdavUpload2
- [ ] apiWebdavUploadTUS

**Comment by kiranparajuli589** [comment]
the mentioned todo is finished :partying_face: :fireworks:
