### ISSUE TITLE
Ideas for settings and settings bundles

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#289]
Lets collect ideas for settings and settings bundles.
Settings bundles are registered by extensions, so please think about which extension is registering the settings bundles.

I will add all ideas here at the top. Please add more through comments.

Every extension can as many settings bundles as needed.

### ocis-accounts
- Profile
  - language
  - timezone

### ocis-phoenix
- Misc (find better name... settings in this bundle are supposed to apply to everything in phoenix)
  - left-to-right or right-to-left
  - branding options - input needed. @LukasHirt could you elaborate?
- Files
  - quick actions. In the near future we will have multiple quick actions. As the column holding them doesn't have much horizontal space, we will need to limit it to having only two or three quick actions. Idea: have settings available letting the user customize what quick actions they want to see. Even cooler would be to scope them by filetypes.
  - default sorting in files list

**Comment by LukasHirt** [comment]
Here is a list of branding which was agreed should be available during runtime:

- Logo on the login page (probably obsolete since there won't be any ocis web app login screen)
- Logo on the top bar
- Primary colour
- Secondary colour
- Background image/colour on the login page (same as with the logo here)
- Icon colours? => requires SVG
- Favicon
- Strings
  - Title
  - Entity
  - Base URL
  - Slogan
  - Logo claim
  - Help URL
  - Imprint URL
  - Privacy Policy URL
  - Branded client download URL
  - Help text on the public link page

Having those themes defined in a file and in the web UI only offer the option to switch them as is done e.g. in iOS client would be perfectly enough IMHO. In case someone would be interested in having some theme editor in the web UI then I'd say that's it's own extension.

**Comment by kulmann** [comment]
Proposal from @PVince81: `upload chunk size` as setting (needs to be limited to administrators, or solved through service configuration instead)

**Comment by LukasHirt** [comment]
What about some extensions management as was in oC10? Enabling/disabling extensions, maybe also installing new ones?

**Comment by refs** [comment]
@kulmann is this discussion still relevant, or can it be closed? I think it needs a higher level concept rather than a discussion on an issue, wdyt?

**Comment by refs** [comment]
This ticket is a living document and it should not be tracked as a GH issue, perhaps move the discussion to Confluence? Closing it for the time being.
