### ISSUE TITLE
Config option to disable caches

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3475]
## Is your feature request related to a problem? Please describe.
If I run multiple instances of a service which have a cache, the cache needs to be shared (common cache) or the cache must be able to be disabled. Both requirements aim at having no inconsistencies between the caches (which is also fulfilled by having no cache at all)

## Describe the solution you'd like
I want to have the possibility to disable all caches, in theses services (examples):
- settings service
- gateway 

## Describe alternatives you've considered
Per service instance caches could work out. But for a lot of things they can be bad or even harmful.

## Additional context
-

**Comment by jvillafanez** [comment]
Instead of having an option to disable the cache, I think it's better to have multiple cache implementations available in the ocis-pkg.
We can have the following implementations at some point:
* Empty implementation: this will act completely transparent as if no cache is used. In practice, this will act as a disabled cache
* Local in-memory: this is an implementation based on a local variable. Designed for services without any replica. This doesn't require any external communication and it should be blazing fast.
* Redis-based: the cache will be backed by redis (or any other similar service, to be decided). Designed for services with multiple replicas so they can share the same cache.

We could also include a custom implementation so the cache of service A1 can communicate with the cache of service A2. While this wouldn't require another centralized service such as redis, it seems quite complex and I'm not fully sure how we can implemented it in an easy way. Anyway, that's another option we could include at some point.

The advantage is that we could switch the implementation without any big change in the code. We can also include and use new implementations at some point if we need them.

For now, I think the empty and the local implementation are the ones that we need in the short term.

**Comment by jvillafanez** [comment]
Implementation plan:
* Phase 1:
  * Define "ocis-pkg/cache/cache.go" as interface for all the caches
  * Create "ocis-pkg/cache/emptycache/emptycache.go" to provide the empty implementation of the cache
  * Create "ocis-pkg/cache/localcache/localcache.go" for a local thread-safe implementation. This is expected to be a copy of the "ocis-pkg/sync/cache.go" file for the most part.
* Phase 2:
  * Remove the "ocis-pkg/sync/cache.go" and replace the instances with the "ocis-pkg/cache/cache.go"
    * Code might need adjustments
    * Base implementation will be the localcache.
* Phase 3:
  * Make configurable whatever cache we need.

Note that a redis-based cache isn't planned for now (we might need to discuss alternatives), but the code will be ready to accept any similar implementation.

**Comment by jvillafanez** [comment]
Expected usage of https://github.com/owncloud/ocis/pull/4337 for the "ocmem" and "etcd" implementations
* The cache client / connector will be the same for all the services
* The caches are thread safe.
* Both caches use the concept of databases and tables to separate data sets.
  * Each service is expected to use its own database and table. For example, the proxy service should use "services" as DB and "service/proxy" as table, while the thumbnails service should use "services" as DB and "service/thumbnails" as table. If any component in the ocis-pkg uses these cache, such as the roles, it can also use "ocis-pkg" as DB and "ocis-pkg/roles" as table. This will prevent key collisions among the services.
* All the features of the go-micro interface are implemented, however:
  * Prefix + suffix searches (at the same time) might perform badly because we might need to request data multiple times. This is handled internally, but it might take time. A prefix search or a suffix search should perform fine.
  * Offsets should be avoided. Neither the "ocmem" nor "etcd" implementations can handle numeric offsets properly, so we need to request additional entries that will be skipped. For example, for an offset of 1000000 and a limit of 2 we need to retrieve 1000002 entries and skip the first 1000000 in order to return only 2 results. The exact same behavior will happen for the next calls.
    * There is no cursor in place to implement pagination. If you search with offset 50 and limit 10, and then with offset 60 and limit 10, this second search will start from the beginning, it won't continue from the last search.
  * Writing is slow. It's likely slow in the first place, but in order to search by suffix efficiently we have to duplicate the data, which involves an additional write. This means that the record will be written twice. This is also done transparently.
* Prefix and suffix searches are expected to perform fine in both "ocmem" and "etcd" implementations. Note that they should be accompanied with a limit, otherwise we might still need to return thousands of records, which of course will be slow.
* Retrieved TTLs are unreliable with the "etcd" implementation. You either get a valid record, or you don't get the record. Expired records won't be returned.

For the "ocmem" implementation:
* There is a size limit (configurable) for each table. The default is 512 entries.
* There is no particular limit of tables that can be in memory. This might become a problem if there are to many table in use even if the size of each table is under control (we might need to look into it)
* A partial LRU mechanism is implemented to make space for new entries in each table. Each table has its own independent mechanism.
* Each table is completely independent of each-other. This include the data, the size limit and the LRU mechanism.
* The data in each table is stored inside two radix trees and one linked list. This will take some additional memory, which might also limit the number of entries we can store.

For the "etcd" implementation:
* There are no particular limits other than the ones imposed by the server itself
* As said, each record will be duplicated and stored with 2 different etcd keys in order to be able to search by prefix and by suffix.
* Reading a record **won't** update the TTL of the record (if any). In order to get the actual TTL we'd need to perform a request per each record, which will be expensive.

Reasonable general limits could be:
* Up to 50 services / components, each one owning one table
* Up to 5000 entries per table, for a total of 250000 entries for the "ocmem" implementation
* TTL usage is highly recommended since there is no particular limit with the "etcd" implementation, and we aren't controlling the number of entries there, so it could grow indefinitely. The TTLs should help to prevent the data from growing uncontrollably.

**Comment by butonic** [comment]
reva gateway is in https://github.com/cs3org/reva/pull/3250
ocis PR to update reva is in https://github.com/owncloud/ocis/pull/4627

**Comment by butonic** [comment]
https://github.com/owncloud/ocis/pull/4627 got merged
