### ISSUE TITLE
--config-file

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#3506]
## Is your feature request related to a problem? Please describe.
When starting an extension without runtime, I want to specify an exact config file.

## Describe the solution you'd like
have a `--config-file` flag, eg. `ocis proxy server --config-file /lorem/foo.bar`

## Describe alternatives you've considered
I could set some environment variables.

## Additional context

CC @mmattel

**Comment by mmattel** [comment]
**Two points:**
* Maybe to do some renaming on top to make it more clear:
`When starting an extension without runtime` --> `When starting a killed runtime extension`

* Consider how to handle this command line option when using docker:
When you are in the shell of the container, kill and restart (run) an extension, you must add this parameter as discussed, but the question raises - compared when using the plain binary - where is this file located physically - because we have the host (where it should be) and the container (where ist should not be)...
I have already set an internal reminder in the admin docs that this needs documentation
Maybe related: https://github.com/owncloud/ocis/pull/3480

Adding @dragonchaser because we discussed this topic today in the morning.

**Comment by wkloucek** [comment]
> **Two points:**
> 
> * Maybe to do some renaming on top to make it more clear:
>   `When starting an extension without runtime` --> `When starting a killed runtime extension`

There is no runtime at all... Even no killed runtime or killed runtime extension.

`ocis server` => starts a runtime and all extensions
`ocis start` => starts an extension in an already running runtime. Fails if no runtime is available
`ocis kill` => stops an running extension in an already running runtime. Fails if no runtime is available

`ocis <extension-name> server` => starts the extension without runtime... There is no running runtime needed nor does it start a runtime. 


> * Consider how to handle this command line option when using docker:
>   When you are in the shell of the container, kill and restart (run) an extension, you must add this parameter as discussed, but the question raises - compared when using the plain binary - where is this file located physically - because we have the host (where it should be) and the container (where it should not be)...

I don't get the problem. You'll need to use volumes if you want to have the config file on your host disk and inside the container. If it's only on the host disk, you can't access it inside the container. But that's how containers work

**Comment by wkloucek** [comment]
I personally no longer see a use case since the current configuration mechanisms seems to be working fine, too
