### ISSUE TITLE
[New/Spaces webdav] HTTP status code differ while listing the contents of another user's trash bin

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#3561]
## Describe the bug

HTTP status code while listing the contents of another user's trash bin is different in spaces WebDAV and new WebDAV.

## Steps to reproduce

1. create user 'user1' and 'user2'
2. as  'user1' upload file 'textfile0.txt' with content 'test'
3. as 'user1' delete file 'textfile0.txt'
4. as 'user2' try to list the trashbin contents of 'user1'

## Expected behavior
In both new/spaces WebDAV, the same HTTP status code
`HTTP/1.1 401 Unauthorized`

## Actual behavior
In new WebDAV, `HTTP/1.1 401 Unauthorized`
In spaces WebDAV, `HTTP/1.1 404 Not Found`

## Setup

<details>
<p>

```console
OCIS_VERSION=latest
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by phil-davis** [comment]
In these scenarios, `user1` is sending a valid password (authentication) but trying to access a resource that `user1` does not have access to. 

For the new WebDAV case, `user1` tries to access a path that "belongs" to `user2`. It seems that the server-under-test decides that the requested resource might be there, but in any case `user1` does not have authority to access the resource, so returns 401.

For the spaces case, `user1` tries to directly access a space, using the space id, that happens to be the personal space of `user2`. (`user1` came to know the space id of that because the test saved it and "handed it" to `user1` - in normal operation it would be difficult for `user1` to find out the space id of personal spaces of other users) I guess that the server-under-test returns 404 "not found" because the requested space id is not in the list of spaces that `user1` can "see".

And there will be another scenario where `user1` "makes up" a possible space id and tries to access it (trying to guess/hack into what might be there on the server) - should that return 401 or 404?

For security reasons, `user1` should not be able to tell the difference between a valid space id that she does not have access to, and a space id that really does not exist at all.

So, what should be the HTTP status returned for these scenarios - 401 or 404?

**Comment by micbar** [comment]
I think for security reasons, 404 is the best option.

@C0rby any opinion on that?

**Comment by C0rby** [comment]
Yeah, I think returning 404 makes sense. :+1:

**Comment by phil-davis** [comment]
I created core PR https://github.com/owncloud/core/pull/40072 which demonstrates an existing difference on oC10.

IMO oC10 should be fixed/adjusted so that it returns consistent 404 "not found" for all this "trying to access another trashbin". And then also make oCIS behave the same way.

**Comment by butonic** [comment]
started implmentation in https://github.com/cs3org/reva/pull/3300
