### ISSUE TITLE
Demo User Creation Question/Improvement

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3593]
Post a discussion with @rhafer:

**Recently the:**

* Creation of demo users has been changed with the new env `IDM_CREATE_DEMO_USERS` which you now actively need to provide.
* The switch from `glauth` to `libreidm` was made and the admin user is created on startup if not exists

**Some question rise:**

* What is necessary to be started that the admin user is created (like runtime, libreidm ect)
* Is it true that _whenever_ ocis starts and NO admin user is found, an admin user is created?
* Is it true that when you have started AND stopped ocis once, that you can create the demo users adding the new env var on the next start?

The answers are docs relevant.

Cant test this on myself as there is no new version available.

@micbar @wkloucek 

@EParzefall FYI

**Comment by rhafer** [comment]
> **Recently the:**
> 
>  * Creation of demo users has been changed with the new env `IDM_CREATE_DEMO_USERS` which you now actively need to provide.

Note: The change that demo user are not created by default any more is already present in 1.20.0, with the next release we're  switching from glauth to libregraph/idm and with that the name of the env var to  enable the demo user creation changes from `ACCOUNTS_DEMO_USERS_AND_GROUPS` to `IDM_CREATE_DEMO_USERS`
 
>  * The switch from `glauth` to `libreidm` was made and the admin user is created on startup if not exists
> 
> 
> **Some question rise:**
> 
>  * What is necessary to be started that the admin user is created (like runtime, libreidm ect)

It happens when the "idm" service is started for the first time, which happens when ocis is started with the default set of services.

> * Is it true that _whenever_ ocis starts and NO admin user is found, an admin user is created?

No. It only happens if the user database does not exist when ocis (or more specifically the idm service) is started. So this basically means the user is only created on first startup.

> * Is it true that when you have started AND stopped ocis once, that you can create the demo users adding the new env var on the next start?

For the idm that is currently not the case (we can of course change that if that is really needed). And for the "old" accounts/glauth based setup the docs (https://github.com/owncloud/ocis/blob/v1.20.0/docs/ocis/getting-started/demo-users.md?plain=1#L10) also say that it only happens on first start. (I haven't checked yet what is really the case for the setup)

**Comment by mmattel** [comment]
**To summarize this:**

* you have to know that you have to set the env variable on first start to let ocis create the demo users
* you cannot create post first start the demo users by setting the env var
* you _could_ delete the idm/boltdb, but then you delete all users created by the bootstrap process including the admin = better to delete the complete .ocis directory and resetup ocis...

=> big frustration potential ...

I will add a note into the admin documentation to describe the behaviour.

**Proposal:**
Implement a way to add demo users post first start (check and add if not present)

**Comment by micbar** [comment]
@mmattel @pmaier1

I would document how to reset the user directory and recreate it with the demo users. IMO this is enough.

IMO this is really a developer context.

If you set up a demo instance for ocis, you would use different users.

**Comment by pmaier1** [comment]
> I would document how to reset the user directory and recreate it with the demo users. IMO this is enough.

agreed

**Comment by mmattel** [comment]
> I would document how to reset the user directory and recreate it with the demo users.

This has already be done and is part of the documentation. The change was implemented when we documented the init command.

Closing
