### ISSUE TITLE
Open descriptions and defaults for environment variables

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3793]
This is a list of all extension where `defaults` **and** `decriptions` are missing. Note that for some elements, the content is most likely the same over many extensions like logging or tracing or JWT token info. In any case, this **MUST** be filled in each extension with the same text - if this is the case. Note that also `default` is a field that must be populated!

Description texts should start with a capital letter. In case existing descriptions start in lower case - change them.

The `users` extensions has good texts for descriptions of the `tracing` stuff (defaults are missing tough).

Regarding the questions, for sure I did not catched them all, but you may see the pattern.

Pls add me in cc to each PR created so I can monitor the changes to trigger the documentation update.

@micbar @wkloucek @butonic pls assign responsibles to extensions by editing the issue. Self assignment of volunteers is welcomed too 😃 

- [x] App Provider :white_check_mark:
- [x] App Registry :white_check_mark:
- [x] Audit :white_check_mark:
- [x] Auth Basic :white_check_mark:
- [x] Auth Bearer :white_check_mark:
- [x] Auth Machine :white_check_mark:
- [ ] Frontend
`FRONTEND_CHECKSUMS_SUPPORTED_TYPES` missing type
- [x] Gateway :white_check_mark:
- [x] Graph :white_check_mark:
- [x] Graph Explorer :white_check_mark:
- [x] Groups :white_check_mark:
- [x] IDM :white_check_mark:
- [x] IDP :white_check_mark:
- [x] NATS :white_check_mark:
Question: `NATS_NATS_STORE_DIR` is there a difference when using binary vs container?
- [x] Notifications :white_check_mark:
- [x] OCDAV :white_check_mark:
- [ ] OCS @dragonchaser 
`OCS_MACHINE_AUTH_API_KEY` and `OCS_ACCOUNT_BACKEND_TYPE` missing description 
- [x] Proxy :white_check_mark:
- [ ] Search
`SEARCH_DATA_PATH` and `SEARCH_MACHINE_AUTH_API_KEY` missing description
- [x] Settings :white_check_mark: 
- [x] Sharing :white_check_mark: 
- [x] Storage-Publiclink :white_check_mark: 
- [x] Storage-Shares :white_check_mark: 
- [x] Storage-System :white_check_mark: 
Questions:
`STORAGE_SYSTEM_OCIS_ROOT` is there a difference when using binary vs container?
`STORAGE_SYSTEM_TEMP_FOLDER` is there a difference when using binary vs container?
- [x] Storage-Users :white_check_mark: 
Questions:
`STORAGE_USERS_OCIS_ROOT` is there a difference when using binary vs container?
`STORAGE_USERS_S3NG_ROOT` is there a difference when using binary vs container?
`STORAGE_USERS_OWNCLOUDSQL_DATADIR` is there a difference when using binary vs container?
- [x] Store :white_check_mark: 
Question: `STORE_DATA_PATH` is there a difference when using binary vs container?
- [ ] Thumbnails
`THUMBNAILS_RESOLUTIONS` missing type and description
Question: `THUMBNAILS_FILESYSTEMSTORAGE_ROOT` is there a difference when using binary vs container?
- [x] Users :white_check_mark:
Question: `USERS_LDAP_CACERT` is there a difference when using binary vs container?
- [x] Web :white_check_mark: 
- [x] WebDAV :white_check_mark:

@EParzefall FYI

**Comment by dragonchaser** [comment]
Ckassified as bug, blocks docs-team!

**Comment by wkloucek** [comment]
@mmattel there are multiple questions about path for different packaging formats / release artifacts. They are valid, since the current configuration documentation doesn't reflect these differences at all.

In the current documentation we have a lot of default values for paths beginning with `~/.ocis`. These paths are all dependent on the packaging / release artifacts:

- for binaries released on our download mirror and GitHub releases, `~/.ocis` from documentation equals `~/.ocis` as base data path in the oCIS binary. (the base config path is `~/.ocis/config`
- for our docker images (containing a oCIS binary) released on dockerhub, `~/.ocis` from the documentation equals `/var/lib/ocis` as base data path in the oCIS binary. (the base config path is `/etc/ocis`)

As of now, there are no other packaging formats / release artifacts.

So the current documentation only covers binary releases.

I could offer that we print something like this in our documentation:

`<packaging dependent base path>/...`

For example `NATS_NATS_STORE_DIR` would have the default value `<packaging dependent base path>/nats`

We could also go with `/<oCIS data root>/...`. If you have a better proposal, please let me know

**Comment by mmattel** [comment]
Colleagues, I have updated the services listed in the comment on top with regards of open items based on the recent env merges. Only a view left, we are close to final 😃

**Comment by wkloucek** [comment]
@mmattel are your `... is there a difference when using binary vs container?` questions answered?

**Comment by mmattel** [comment]
**Update:** after a discussion with @butonic, when having a container and with all env's where you define a filesystem path, that path is INSIDE the container and must be made available to the OS if you want to keep data persistent. I will update the documentation accordingly.
