### ISSUE TITLE
Add the term "API Gateway" to the proxy documentation

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#3861]
Following a discussion in RC, when we talk about the proxy extension, we should add the term `API Gateway` embedded in a descriptive text to better explain what the extension does.

@wkloucek @dragonchaser

**Comment by wkloucek** [comment]
This is a long standing issue: https://github.com/owncloud/ocis/issues/1432

**Comment by wkloucek** [comment]
My view on this is, that we have multiple api-gateways:
- cs3 api gateway, now called "gateway" and coming from reva
- dataprovider api gateway, now part of the frontend service and coming from reva
- http api gateway, now called "proxy" and coming from oCIS

One could argue about the dataprovider api gateway, because it sits behind the proxy, but still it routes requests by metadata.

**Comment by mmattel** [comment]
As I read this, there are three different API gateway types:
* http related
* cs3 related
* dataprovider related

The challenge is, to have a proper description what each gateway exactly does and how it differenciates from the others.

**Comment by micbar** [comment]
not so important before GA, other topics like backup and restore are more imporant

**Comment by micbar** [comment]
bumping

**Comment by mmattel** [comment]
not stale

**Comment by mmattel** [comment]
You are right. In this repo, the fix started with #4911 and its correspondent docs-ocis PR and will be finalized with the above referenced docs-ocis PR. Thanks for highlighting.

**Comment by mmattel** [comment]
https://github.com/owncloud/docs-ocis/pull/301 has been merged, closing
