### ISSUE TITLE
Adjust Testsuite to async uploads

### ISSUE THREAD

**Issue by kobergj** [owncloud/ocis#4095]
Async uploads are implemented on the shiny new `experimental` branch https://github.com/cs3org/reva/pull/3029 
The idea is that the server returns immediately after he has received all bytes, then handle postprocessing asynchronly. 
With virusscanning around the corner and potentially more features that make use of async postprocessing mechanism  it would be nice to have all that properly tested. 

Unfortunately the testsuite in its current state cannot handle async uploads. There a mainly two reasons for it

#### `425` status code while processing

During postprocessing of a file the server will send status code `425` on propfinds or get requests. This is because the file is not ready yet and can therefore not be downloaded until processing is finished. The server does send metadata information already with the `425` status code, so for most tests it might be sufficient to just ignore the status code of the response and continue checking file metadata. However tests that actually download a file and check its content need to wait until the processing is finished and the server returns a `200` status code again.

#### Last Updated time

Some tests check for the `Modified` time of a file. They do expect it to match a specific timestamp. However, if postprocessing is finished, the file will get a new timestamp. This is because the file is now processed and ready to download, so the etags need to be updated. These checks probably need to be omitted, or one could just check that the actual timestamp is after the original expected one.

These are the two main issues which (I hope) will allow most tests to run async. There might be more adjustments needed. But I can't say for sure because of too many failing tests.

**Comment by kobergj** [comment]
cc @micbar @individual-it

**Comment by phil-davis** [comment]
Thoughts:

- for downloads we can just embed an extra loop when running on oCIS or reva. If `425` is returned then the test code can wait 1 second and try again. And we put some limit on the loop so that it stops after "a while" (however long we think is the maximum time that the server should to take realistically to "process" an uploaded file)
- modified time - if the upload sends an `mtime` along with the upload, then the server should respect that. If no `mtime` is specified then the server is free to assign an `mtime`. The test code can be less fussy about the `mtime`. I  thought that we already had some flexibility for this already, but I need to check. Because the test-runner and the system-under-test can run in different systems anyway, which might have their system time slightly different, and the `mtime` can anyway be 1-second later than what the test-runner "expects" because the time might be "12:30:51.98" when the test-runner starts an upload, and by the time the system-under-test receives the upload it is "12:30:52.01" - I will have a look for where we already put this flexibility.

**Comment by kobergj** [comment]
Sorry, got this ticket got lost for me somehow :disappointed: 

I have now created a PR that tests with async uploads. I can change the core commit id if needed: https://github.com/owncloud/ocis/pull/5251

To activate async uploads for local testing one only needs to set the `STORAGE_USERS_OCIS_ASYNC_UPLOADS` envvar to `true`. When trying to test edge cases one can additionally set `DELAY_POSTPROCESSING` envvar to e.g. `10s` to artificially delay postprocessing on the server

**Comment by individual-it** [comment]
ToDo:
- [ ] run all tests with enabled async upload and check what is failing and why. (it could be a bug or it could be that tests need to be adjusted to wait)
- [ ] create new tests with `DELAY_POSTPROCESSING` to make sure the API really returns `425` while post-processing (@kobergj  any headers that are worthwhile to test?)

**Comment by kobergj** [comment]
No additional headers to test. Files in postprocessing should mainly behave the same as normal files. Except:
- The status code in the `PROPFIND` will be `425` 
- Trying to download the file will result in a `425`

**Comment by kobergj** [comment]
Two issues here: 
- web doesn't show the `425` file here because the async uploads ui is not yet merged
- You understand it correctly that file show become `200` after a while. You run plain ocis master? No additional envvars set?

**Comment by ScharfViktor** [comment]
> * You understand it correctly that file should become `200` after a while. You run plain ocis master? No additional envvars set?

@kobergj  I run ocis with `OCIS_INSECURE ` and while some time code changed to `200`

**Comment by ScharfViktor** [comment]
https://github.com/owncloud/ocis/issues/5256
