### ISSUE TITLE
[qa-team] do not run tests including `/Shares` folder with spaces DAV version

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#4154]
`/Shares` is not a folder anymore.

In Copy API tests we have tests for comparing etags of /Shares folder. While using `spaces` dav version, `/Shares` is no more a folder and we do not get any etag for it.

So the current personal space tests are now invalid and 
- [x] should be removed from the `ownCloud/core` API tests https://github.com/owncloud/core/pull/40194
- [x] should be rewritten & placed inside ocis (dedicated ocis tests) https://github.com/owncloud/ocis/pull/4174

A demonstration of the test failures can be found here: https://github.com/owncloud/ocis/pull/4137

_Originally posted by @individual-it in https://github.com/owncloud/ocis/issues/4137#issuecomment-1179944016_

**Comment by kiranparajuli589** [comment]
there are more scenaios including `Shares` folder and running with spaces DAV

**Comment by SagarGi** [comment]
@phil-davis and @individual-it  There are lots of tests that are in expected to failure on ocis tagged with this issue  https://github.com/owncloud/ocis/issues/2968

Since `/Shares` related implementation is not available in core we might want to run those tests on ocis. We can shift all the tests realted to `/Shares` on ocis and minimize the expected to failure. I need some information whether or not to shift, so that i can create a TODO for all the tests.

**Comment by SagarGi** [comment]
We have many expected to failure related to `/Shares` on ocis .Since `/Shares` related is not implemented on core so better to
shift them on ocis.

https://github.com/owncloud/ocis/blob/50cb1912103d1a9d0db2ef4197bcef52855e0a20/tests/acceptance/expected-failures-API-on-OCIS-storage.md?plain=1#L994-L1098

TODO QA team:
 
Suites to shift on ocis:

- [ ] apiFavorites
- [ ] apiMain
- [ ] apiShareOperationsToShares2
- [ ] apiWebdavProperties1
- [ ] apiWebdavUploadTUS
- [ ] apiWebdavEtagPropagation1
- [ ] apiWebdavLocks2
- [ ] apiShareOperationsToShares1
- [ ] apiWebdavMove2

NOTE: Task can be divided and please follow up the expected to failure and shift accordingly since there are multiple features for a single suites.

**Comment by SagarGi** [comment]
This PR https://github.com/owncloud/core/pull/40311 also contains `/Shares` related tests and i have not added `spaces` webdav for it. We can directly add it to `ocis` local api tests:

ToDo
- [ ] Add above tests in ocis

**Comment by amrita-shrestha** [comment]
all repo has been covered so closing this issue.
