### ISSUE TITLE
Admin need permission to delete orphaned project spaces

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4196]
2.0.0-beta.5

Steps: 

- user Katherine creates project space (without manager members)
- admin deletes Katherine

 
Expected: admin must be able to manage the space. Share space between users or delete space
Actual: admin cannot manage orphaned project spaces

**Comment by rhafer** [comment]
> We should add a permission "can edit all spaces" (memberships) "can delete all spaces"

Should that new permission really apply  _all_ spaces? Or should it only apply to just spaces of type "project"? I am asking because in https://github.com/owncloud/ocis/pull/4447 we're adding a new permission "delete-all-home-spaces". So I guess it would make sense to either have "delete-all-home-spaces" and "delete-all-project-spaces" as sepearte permission. Or just introduce a single new "delete-all-spaces" permission that allow to delete spaces of any type.
@micbar which option would you prefer?

**Comment by micbar** [comment]
`delete-all-project-spaces` is a bit problematic IMO because this is based on the assumption that we have spaces of this type. Makes it hard to work with arbitrary space types. So i would prefer `delete-all-spaces`
