### ISSUE TITLE
Implement cache

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/ocis#4427]
We need a cache that replaces our current in-memory approach that is causing issues (see: https://github.com/owncloud/ocis/issues/4251) and has been disabled for now (see: https://github.com/cs3org/reva/pull/3167).
We should introduce a go-micro store interface to be able to swap out the cache implementation as necessary (e.g. nats, go-micro...)

**Comment by micbar** [comment]
@jvillafanez started this already in #4193

**Comment by michl19** [comment]
This ticket concerns Reva. #4337 is about oCIS

**Comment by butonic** [comment]
![cache-store-invalidation drawio](https://user-images.githubusercontent.com/956847/191224116-b69c0af0-035a-4f0b-826e-d531cd2910a5.png)

- [ ] Datagateway needs to invalidate cache after successful PUT / upload
- [ ] InitiateFileUpload dous not need to invalidate cache

**Comment by jvillafanez** [comment]
> Datagateway needs to invalidate cache after successful PUT / upload

What if the datagateway sends a notification to the gateway so it's the gateway the one invalidating the cache? This way, the gateway keeps the ownership of the cache and no other services need to access nor modify that cache.

The alternative could be to implement a `StatCache` component to own the cache, so both the gateway and datagateway services can use it in the same way the role manager is being used now. The risk in this case is that the `StatCache` component must be backed up by the same cache.

The first approach seems to be better. Even if the gateway uses an isolated in-memory cache the cache would still work because it will be the gateway the one invalidating the cache

**Comment by butonic** [comment]
Currently Reva has no event bus. only ocis has. Which is why I went with the StatCache (and other) shared implementations: https://github.com/cs3org/reva/pull/3250

**Comment by butonic** [comment]
https://github.com/owncloud/ocis/pull/4627 got merged
