### ISSUE TITLE
CI: duplicate CI run with only chat notification

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#4460]
## Describe the bug

When creating pull request https://github.com/owncloud/ocis/pull/4459 I noticed that two independent CI runs were started:
1. https://drone.owncloud.com/owncloud/ocis/14958 (seemingly normal CI run)
2. https://drone.owncloud.com/owncloud/ocis/14957 (only chat notification, nothing else)

## Steps to reproduce

See linked pull request. I don't know what triggered the second CI run.

## Expected behavior
Only one CI run.

## Actual behavior
A seemingly normal CI run and one that only performs a chat notification.

cc @individual-it @phil-davis

**Comment by phil-davis** [comment]
I made a local branch `release-1.1.1-alpha.1` and added this commit to it:
https://github.com/owncloud/ocis/commit/8371d25c1b62fc9e59082c3129970aa7a5e523ca

Then pushed it to GitHub:
`git push --set-upstream origin release-1.1.1-alpha.1`

I have not even started making a PR.

This drone CI triggered "automagically" on push: https://drone.owncloud.com/owncloud/ocis/14963

I did a similar typo fix in commit https://github.com/owncloud/ocis/commit/dd08eb8722bac8cbff1925f81a7c200783f71801 which I put in a branch called `fix-typo-2022-08-26` - no drone triggered "automagically".

There is something special about branches that having names starting with "release". I don't think that is in `.drone.star`. Maybe there is a setting in the oCIS GitHub repo that causes that "CI on push" to be triggered.

`.drone.star` is probably not doing the build and test pipelines because the pipelines have trigger restrictions like:
```
        "trigger": {
            "ref": [
                "refs/pull/**",
            ],
        },
```
so if a drone build is somehow triggered for some commit that is not part of a PR, then the pipelines are not created.

IMO  the behavior of `.drone.star` is what is wanted. We just need to find out how to stop those "push" builds from triggering when a release* branch is created.

**Comment by phil-davis** [comment]
Are the settings somewhere in:
https://drone.owncloud.com/owncloud/ocis/settings
or in https://github.com/owncloud/ocis settings? (which I do not have access to)
@kulmann

**Comment by kulmann** [comment]
> Are the settings somewhere in:
> https://drone.owncloud.com/owncloud/ocis/settings
> or in https://github.com/owncloud/ocis settings? (which I do not have access to)
> @kulmann

I checked the webhook config and further automation settings in the ocis repo. Didn't find anything.

**Comment by phil-davis** [comment]
I looked harder:
```
        "trigger": {
            "ref": [
                "refs/heads/master",
                "refs/heads/release*",
                "refs/tags/**",
            ],
            "status": [
                "failure",
            ],
        },
```

We want that special `refs/heads/release*` - when a branch has a name starting with `release` then we want to notify to the chat. But that is happening on the first push of the branch (as well as when the PR has been created). On  the first push of the branch, the other `"refs/pull/**"` triggers do not apply (there is no PR yet), and so we do not get any other pipelines.

Actually we want to pick out this "special" subset of PRs and notify rocketchat if they fail. The trigger ref needs to be something like:
```
               "refs/pull/**" && "refs/heads/release*",
```

Now to see if there is a way to write "complex" logic in the trigger section of a pipeline.

**Comment by kiranparajuli589** [comment]
https://community.harness.io/t/can-we-add-complex-logic-in-the-pipeline-trigger/12641
