### ISSUE TITLE
OCIS binary ignores PHOENIX_* env vars

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#454]
See https://github.com/owncloud/ocis/issues/450#issuecomment-673397996

It appears that despite using the PHOENIX_ env vars, the ocis-phoenix still has side effects.

to verify, I ran `PHOENIX_ASSET_PATH=~/work/workspace/ PHOENIX_WEB_CONFIG=~/work/workspace/phoenix/config-ocis.json OCIS_LOG_LEVEL=debug bin/ocis-debug --log-level=debug server > /var/tmp/ocis/ocis.log 2>&1` where there's no Phoenix in the ASSET_PATH.

=> the UI still renders..

so this means those env variables are not used at all...

in the past I believe I've usually set those while running ocis-phoenix, not ocis...
we should fix this...

**Comment by kulmann** [comment]
Addressed in https://github.com/owncloud/ocis-phoenix/pull/76 and https://github.com/owncloud/ocis-phoenix/pull/77.

**Comment by kulmann** [comment]
Already closing, since https://github.com/owncloud/ocis-phoenix/pull/76 is merged and was the critical one. Missing config was already shown in the web ui. https://github.com/owncloud/ocis-phoenix/pull/77 only aligns the service behaviour for an invalid config path with the one for an invalid asset path.
