### ISSUE TITLE
Memory consumption too high / Memory Leak?

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#4628]
## Describe the bug

Running oCIS on a Raspberry Pi with 1 GB of memory does not work any more. oCIS starts up properly, but gets killed after the memory has grown to the limit of nearly 1GB.

It is not relevant if it is a Raspberry Pi or another system, it needs to be known and clear where the increased memory demand comes from or if it is a memory leak. 

## Steps to reproduce

Just start oCIS on a Raspberry Pi.
Test System: Raspberry Pi 3B with 1GB of RAM, running Raspbian Lite.

## Expected behavior
oCIS should run on a Raspberry Pi with 1GB of memory properly.

**Comment by micbar** [comment]
We need to find out:

- [ ] Do we have a memory leak?
- [ ] Is the memory  footprint in general too high?
- [ ] Is the problem located in bleve or in the ocis implementation?

**Comment by rhafer** [comment]
![profile001](https://user-images.githubusercontent.com/373399/191966869-0325006f-d8bc-4aa0-be57-64f1e9f0c2e5.svg)

This issue seems to be cause by some overly large caches that a configured in the reva auth provider. They alll hardcoded to 1 Million cached items and upon startup the cache implemenation does this: `c.items = make(map[interface{}]*lfuItem, c.size)` which causes a huge allocation. :boom:

**Comment by rhafer** [comment]
After lowering the cache to 10000 items (which is still quite large for a user cache IMO) looks a lot better (down to 60MB, from more than 1GB after startup):

![profile002](https://user-images.githubusercontent.com/373399/191968766-5745627f-2a41-4d67-9020-f05e5898e59e.svg)
