### ISSUE TITLE
Identical shares have different naming convention in `oc10` and `ocis`

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#4674]
## Describe the bug

When a user receives the identical share from different user the naming convention of the file/folder is different to that of oc10. Let's say a user has accepted the share `foo` from two different users,   in the case of oc10 the name will be `foo`, `foo (2)` while for ocis it's  `foo`, `foo (1)`

## Steps to reproduce

1. As `einstein` create a folder `foo/` and share it to user `moss`
2. As user moss accept the share
3. As user `marie` create a folder `foo` and share it to user `moss`
4. As moss accept the share

## Expected behavior
I'm putting `oc10` as expected. The shares should be displayed as `foo` and `foo (2)`

## Actual behavior
The shares are displayed as `foo` and `foo (1)`
![acceptsimilarshareafterreload](https://user-images.githubusercontent.com/41103328/192469485-7c358d69-6bd5-4379-a2c5-11d909975e81.png)

## Setup

Latest master

**Comment by SwikritiT** [comment]
Similar issue here: https://github.com/owncloud/ocis/issues/4289

**Comment by micbar** [comment]
Cosmetic, but could save support times 😄

**Comment by kulmann** [comment]
Whatever we decide here also might have effect on the current implementation of file/folder conflict handling in web. More specifically, whenever we find a file or folder name that already exists (e.g. upload, copy, move, create new folder, create new file) we propose new file/folder names starting with `(1)`.

E.g. if you have a folder `test`, try to upload a folder test and choose `Keep both` in conflict resolution, web will use `test (1)` as new folder name. I personally like that. Starting to count at `(2)` is not my personal preference.

For comparison, when creating copies of a file/folder in macOS finder, the behaviour is as follows:
1. have a folder `test` 
2. copy and paste once -> copy receives name `test copy`
3. copy and paste another time -> copy receives name `test copy 2`
(nothing in parenthesis and the first printed number is 2, because the 1 is omitted on the first copy).

Would be interesting to see what Windows or Linux have to offer in that regard.

Since the file/folder name conflict handling in web and the share name duplicate handling in oCIS do in fact match, I'd vote for not changing it and accepting the difference between oCIS and oc10. Happy to discuss.

cc @tbsbdr @pmaier1

**Comment by kulmann** [comment]
@SwikritiT could you please fill out the bug description text? 😇

**Comment by phil-davis** [comment]
My Ubuntu 20.04 UI does this:

![Screenshot from 2022-09-28 08-17-12](https://user-images.githubusercontent.com/1535615/192674451-99612f69-dc9c-4dee-9e8f-e62998972b34.png)
 
If I don't want to Replace (overwrite) an existing file, then I have to enter a new name myself. There is no auto-generating of a new file name.

**Comment by SwikritiT** [comment]
> @SwikritiT could you please fill out the bug description text? innocent And for `latest master` a commit id would be beneficial (but IMO not needed for this particular issue).

Done!

**Comment by micbar** [comment]
@pmaier1 Please let us decide that quickly.

I am fine with starting with (1) for the first duplicate.

**Comment by pmaier1** [comment]
> I am fine with starting with (1) for the first duplicate.

I'm fine with that, too.

**Comment by phil-davis** [comment]
@SwikritiT please sort out the tests so that they understand what is the numbering for oCIS (from 1) and oC10 (from 2).
Have a think about the best way to do it - do we put it in the test code, or explicitly in feature files or?

**Comment by SwikritiT** [comment]
> @SwikritiT please sort out the tests so that they understand what is the numbering for oCIS (from 1) and oC10 (from 2). Have a think about the best way to do it - do we put it in the test code, or explicitly in feature files or?

Okay!

**Comment by individual-it** [comment]
I think there is still a bug with how the names are generated, the code does not seem to look into the current situation, but remembers the counter:
1. as user1 create a folder
2. as user2 create a folder with the same name
3. as user1 and user2 share the folder with user3
4. as user3 accept both shares
5. as user1 and user2 delete the shared folders
6. as user1 and user2 forget everything about what you have done
7. repeat steps 1-4
8. now for user3 the folders are called `folder` and `folder (2)`
9. repeat steps 5-6
10. repeat steps 1-4
11. now for user3 the folders are called `folder` and `folder (3)`

![image](https://user-images.githubusercontent.com/2425577/193210452-88884188-6699-444f-ac65-ca1d11987609.png)

**Comment by rhafer** [comment]
> I think there is still a bug with how the names are generated, the code does not seem to look into the current situation, but remembers the counter:
> 
>     1. as user1 create a folder
> 
>     2. as user2 create a folder with the same name
> 
>     3. as user1 and user2 share the folder with user3
> 
>     4. as user3 accept both shares
> 
>     5. as user1 and user2 delete the shared folders
> 
>     6. as user1 and user2 forget everything about what you have done
> 
>     7. repeat steps 1-4
> 
>     8. now for user3 the folders are called `folder` and `folder (2)`
> 
>     9. repeat steps 5-6
> 
>     10. repeat steps 1-4
> 
>     11. now for user3 the folders are called `folder` and `folder (3)`

This seems to be a duplicated of: https://github.com/owncloud/ocis/issues/8471 which has been fixed.

For sharing NG there is a related issue, we're currently trying to address: #8961
