### ISSUE TITLE
Configure IDP only in proxy / simplify authflows

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#472]
After some internal discussions we would like to question the fact that a lot of services in the ocis-stack need to know about the IDP which makes the configuration quite complicated. Architecturally this seems also to be wrong as every backend-service should be able to work with the "Backend-Token"

Services that currently talk to the IDP:
- Proxy
- Phoenix (special case as it provides a client but might also be getting its idp-config from the proxy)
- Graph
- Reva-Services (which exactly?, why? Can't they just use the token created by the proxy @butonic)  
- More?

Wanted behavior:

- Only clients and the proxy should need to know about the IDP as everything else can use the reva token.
- Only configure the IDP once, preferably in the proxy. 

Following above assumptions reva-auth-* services could be removed as this is handled by the proxy?

**Comment by butonic** [comment]
revas auth providers can authenticate basic and bearer requests. if ocs and ocdav are moved out the authentication in reva can completely rely on the internal access token.

The question is how basic auth will work, because we currently fall baclk on the implementation in reva.

The other aspect is that we need to clarify what an extension can rely on. Which becomes important when thinking about deploying the thumbnailer service along oc10, which has no ocis-proxy ... or we require it in front of oc10. something to document. if we can assume that ocis-proxy is in front of every ocis extension, then they can rely on the access token. but the downside is that, well, they depend on the proxy, the accounts service and glauth, afaict.

**Comment by butonic** [comment]
The proxy should use the CS3 api to authenticate requests, which means making a call to the CS3 gateway. Then, the gateway will dispatch the authenticate request to whatever implementation is necessary / available / chosen. That the proxy implements any auth itself is not how the CS3 API is designed.

Tracking this as https://github.com/owncloud/ocis/issues/4701
