### ISSUE TITLE
Add `shareId` and `shareRoot` in OCS response

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#4726]
Web needs the `shareId` and `shareRoot` of an outgoing share in the OCS response (similar to how it's done in the `PROPFIND` and `REPORT` requests). This is important for the following scenario:

* `userA` has `folder/file.txt`
* `userA` shares `folder` with `userB`
* `userB` re-shares `folder` with and `file.txt` with `userC`
* Now user `userB` requests his outgoing shares via the OCS endpoint: the 2 shares are listed. However, for both shares, we need the `shareId` and `shareRoot` of the parent share (`folder` in this case) to properly resolve the share.

**Comment by JammingBen** [comment]
@micbar fyi as briefly mentioned, this currently is a GA-blocker for Web.

**Comment by kulmann** [comment]
`shareRoot` is needed as well :-)

**Comment by phil-davis** [comment]
* `userA` shares `folder/file.txt` with `userB`
* `userB` re-shares `folder` with and `file.txt` with `userC`

I do not understand this. If `userA`  has shared `folder/file.txt` with `userB` then `userB` receives just `file.txt`.

So how does `userB` re-share `folder` ?

**Comment by JammingBen** [comment]
@phil-davis Sorry, I adjusted the scenario to make it clear: `userA` has `folder/file.txt`, but only shares `folder`.

**Comment by butonic** [comment]
Do I understand correctly that you would like to see a new property `share_id` and `share_root` in every share entry of the outgoing shares list?

### `share_id` is a confusing name and a bad concept
`share_id` is not very descriptive, especially since we have `id`, which is the id of the share itself. There is `parent` but that is used for group shares, which are the parent of user individual accepted shares to store their mountpoint. Maybe `parent_share_id`, but really that does not make any sense. Let me elaborate:

The ocs api to manage shares is implemented by the dedicated share manager service. ocs does stat the storage provider to get file information, which is very slow, but we are caching the stat results aggressively to mitigate the latency penalty of effectively having toe do a stat per share.

The child parent relationship cannot be stored in the share manager, as file scan be moved around, in this case `/folder/file.txt` might be moved to `/otherfolder/file.txt` by `userA`. So, whenever listing shares we would have to compare the path of every shared resource if one of them is a child of another one. That scales exponentially. Not good.

Why do you have to resove that parent/child relationship? What are you trying to do? Maybe I have an idea of how to solve that.

### `share_root` is what?
In `PROPFINDS` we have `oc:spaceid`. But what is `share_root`?

**Comment by JammingBen** [comment]
@butonic `parent_share_id` would be a more fitting name, yes.

> Why do you have to resove that parent/child relationship? What are you trying to do? Maybe I have an idea of how to solve that.

We need this ID to properly build URLs in the share jail. These URLs look like: `https://host.docker.internal:9200/files/spaces/share/from-jannik?shareId=1284d238-aa92-42ce-bdc4-0b0000009157%3Adf05dd65-6787-460c-a83f-90d4fe05318e%3A4214c7b3-ac6e-4a45-a099-9b241c3592b0`. Without the `shareId`, the URL would not resolve correctly.

This is no problem on the "Shared with me"-page. As soon as you navigate into a folder that has been shared with you, its ID will be stored as query param like above.

But it becomes a problem on pages that gather resources from various spaces, like the search result page, or the "Shared with others/via link" view. Because again, we need the `shareId` to properly resolve into the share jail. It already works for the WebDAV report endpoints. I don't now how this has been solved technically, but this endpoint provides the `shareId` and the `shareRoot` for received shares (and their contained resources). And that exactly we need for the OCS API.

> In PROPFINDS we have oc:spaceid. But what is share_root?

I believe it's the mountpoint of the parent share for the share recipient. So if receiving and accepting the share `FolderA`, the `share_root` would be `FolderA/` for this resource and all resources inside.

**Comment by butonic** [comment]
You could glue together the sharejail space id `a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668` with a shares `path` property and navigate using that, e.g.:
`https://{{HOST}}/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/folder/subfolder` when a share has the `path` `/folder/subfolder`.

The `a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668` space is hardcoded and the share jail space, which lists all (only) mounted spaces is used by the desktop client.

For now, the share id is not needed to navigate into a share.

The ultimate goal is to navigate by an arbitrary root node and a relative path. That is already possible at the `/dav/spaces/{root}/{path}` endpoint. In the browser URL we will use the space alias and the part of the path that is visible to the recipient. Actual navigation happens by resource id.

**Comment by micbar** [comment]
@JammingBen @butonic Fine for now? Then please close with a  comment.

**Comment by kulmann** [comment]
We need to check that in web before we can close here.

**Comment by JammingBen** [comment]
We've found a solution by resolving reshares via the private link component in Web, which handles redirects via fileId only. This is okay for now, though not ideal. In the future, Web will be capable of resolving link via fileId regularly.

Anyway, the `shareId` is not needed in the OCS API then.
