### ISSUE TITLE
[Spaces] Change Space names in /graph/v1.0/me/drives to be more useful for clients

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ocis#4844]
"Personal" Space and "Shares" Space have very strange names in the API response from `/graph/v1.0/me/drives`

```
            "driveAlias": "personal/mstingl",
            "driveType": "personal",
            "id": "1284d238-aa92-42ce-bdc4-0b0000009157$6b6253d5-cea6-4533-bd59-a34d160ffd24",
            "lastModifiedDateTime": "2022-08-19T07:36:07.599009932Z",
            "name": "Michael Stingl",
```

```
            "driveAlias": "virtual/shares",
            "driveType": "virtual",
            "id": "a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668",
            "lastModifiedDateTime": "2022-08-19T07:45:22.617232822Z",
            "name": "Shares Jail",
```

In the desktop and mobile clients, it should look like this:

![CleanShot 2022-10-18 at 17 51 19@2x](https://user-images.githubusercontent.com/214010/196480683-53a098cc-0e67-4ed5-8e6b-9bd4d92f62ce.png)

Currently, desktop and mobile clients have "Personal" and "Shares" hardcoded, but it would be much better if the correct, user-facing names, would come from the API.

/cc @TheOneRing @felix-schwarz @kulmann @micbar

**Comment by micbar** [comment]
@michaelstingl @pmaier1 

I see no problem in renaming `Shares Jail` into `Shares`

But for the personal Space i don't like the idea of naming them all the same. On the graph api we can sort spaces by 

1) Name
2) type
3) Date Last modified

Not being able to sort spaces by name in a meaningful way could bite us in the future. You could argument, that this is not a problem because we currently have no listing of personal spaces. But IMO we do not know what possible extensions and future features will do with the personal spaces. I would be happy to find a client side solution on the space name or change the server to something unique per space.

@kulmann @TheOneRing @felix-schwarz

**Comment by pmaier1** [comment]
I think that every user should see their personal Space as 'Personal', not by their display name or similar. 'Shares' should be shares and other (project) Spaces should be called by their name. This is of course for client UIs and those would be happy to get this information from the server in order to not require hardcoding. The API could maybe still offer different information additionally?

**Comment by kulmann** [comment]
FYI in web we rewrite the name of the own personal space to `Personal` for further display usage. That matches with @pmaier1 opinion.

**Comment by micbar** [comment]
@kulmann @pmaier1 Yes you are both right, i see it the same. My only point is, to move the "Personal" Space name to the clients. They need to translate it anyway.
