### ISSUE TITLE
copy API testinfrastructure to ocis repository

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#5094]
To make it easier to administer different oCIS branches and the respected tests it might be better to copy all the test-infrastructure from the core repository to oCIS.
This should reduce the dependencies between repositories and the work to bump the commit ids, but if changes are needed in oc10 it might increase the effort. But oc10 changes should not happen much in the future.

**Comment by individual-it** [comment]
CC @micbar

**Comment by kiranparajuli589** [comment]
@individual-it @phil-davis @micbar With #5280, just the tests infrastructures are moved. Now the local API tests are independent with oC/core but the oCIS CI still depends on oC/core repository to run core API tests and will be necessary to run parallel deployment tests (which needs OccContexts and testing app like things) if we enable it.

**Comment by phil-davis** [comment]
"copy all the test-infrastructure from the core repository to oCIS"

@individual-it I just want to clarify what "all" means:

- test helpers code
- test code (that is found in `tests/acceptance/features/bootstrap`)
- test scripts (like `run.sh` and lint scripts...
- API acceptance test feature files that are currently in oC10 core

And after this issue is done, the ocis CI will not need to fetch the core oC10 repo at all.

**Comment by phil-davis** [comment]
"parallel deployment tests" - hmmm, we will need to think about how we support those.

The drone script in ocis CI can still know how to install an oC10 and set the needed env vars etc to get the parallel deployment installed and working.

Then we will need to look at what test scenarios that we really want to run against a parallel deployment. If we really need to change oC10 settings/options at test startup, or scenario Given steps, then we will need to make the CI have the testing app installed in oC10, and copy the needed `OccConext` etc code into ocis so that it can be used.

**Comment by saw-jan** [comment]
IMO, this can be closed and we can open new issue for clean up tasks

CC @phil-davis @individual-it

**Comment by saw-jan** [comment]
Task has been completed. Create cleanup issue https://github.com/owncloud/ocis/issues/5337
So, closing here!
