### ISSUE TITLE
Restoring an old version is not allowed if the quota is exceeded

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#5144]
ownCloud Web UI 6.0.0-rc.8 
 Infinite Scale 2.0.0-rc.2+1c246bb3b Community 

Steps:
- admin creates space 10 bytes: 
`curl -k -X POST 'https://localhost:9200/graph/v1.0/drives' -u admin:admin -d '{"name":"marketing", "quota": {"total": 10}}' -vk`
- admin creates `file.txt` 8 bytes
- admin reduse file to 4 bytes
- admin creates new file 5 bytes
- admin restores `file.txt` 8 bytes

Actual: 
![Screenshot 2022-11-28 at 18 12 30](https://user-images.githubusercontent.com/84779829/204340601-f6e788de-8068-4cf6-8337-9c30461caa1b.png)

Expected: cannot restore a file because the quota is exceeded

**Comment by micbar** [comment]
@ScharfViktor Thanks for testing.

Expected: The file should be restored and the quota should be exceeded.

That is since a long time an ownCloud Core feature. 

The product philosophy here is like "everybody who can write, should be able to restore under all circumstances, even if quota restrictions prevent it" Every write operation has the potential to harm existing data. In your case, overwrite the file content. The actor should be able to repair his damage in "self service". This reduces the number of helpdesk requests drastically as @hodyroff always tought me. (correct me if I am wrong)
