### ISSUE TITLE
Extended support for localization languages

### ISSUE THREAD

**Issue by Pro100x3mal** [owncloud/ocis#5288]
Please expand support for different languages. At least at the level of ownCloud classic. Is it planned to add the Russian language?

**Comment by mmattel** [comment]
Hello @Pro100x3mal we are using [Transifex](https://www.transifex.com/owncloud-org/owncloud-web/translate/#ru) for our translations, you can add your translation proposals there - you support is very welcomed 😄 The link is for the webinterface of Infinite Scale and contains a couple of sources.

**Comment by micbar** [comment]
This is the link for the russian language https://www.transifex.com/owncloud-org/owncloud-web/language/ru/

**Comment by kulmann** [comment]
Russian is already in the transifex project that @mmattel linked in his post (thank you martin!). Better translation coverage is very welcome.

The web ui current master already fetches russian translations and also serves them if you don't set the language in the settings UI (fallback to browser language).

I will make a PR to ocis early in January so that ocis also offers Russian as language in the settings UI. If you manage to improve the translation coverage in the meantime, the initial user experience will be better. 😎

Maybe @ScharfViktor can also help with translations when he's back from holidays.
