### ISSUE TITLE
Blank Login page with podman container

### ISSUE THREAD

**Issue by big1tasty** [owncloud/ocis#5436]
After trying to deploay ocis with the following steps:
init:
```
podman run --rm -it \
--name ocis \
-e PUID=1000 \
-e PGID=1000 \
-v ocis-config:/etc/ocis \
-v ocis-data:/var/lib/ocis \
--network cloudflare \
--network ocis \
docker.io/owncloud/ocis init
```
deploy:
```
podman run -d \
--name ocis \
--restart unless-stopped \
--label "io.containers.autoupdate=image" \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Europe/Rome \
-e OCIS_INSECURE=false \
-e PROXY_TLS=false \
-e PROXY_ENABLE_BASIC_AUTH=true \
-e OCIS_URL=https://ocsi.{mydomain}.com \
-e IDM_ADMIN_PASSWORD="{super_secret_passwort}" \
-e IDM_CREATE_DEMO_USERS=false \
-v ocis-config:/etc/ocis \
-v ocis-data:/var/lib/ocis \
--network cloudflare \
--network ocis \
docker.io/owncloud/ocis
```

i get a blank login screen:
![image](https://user-images.githubusercontent.com/64231135/213557249-8ea31adc-d10e-43d6-80f0-430519c7f37d.png)

With the following logs in ocis container: 
```
{"level":"error","service":"graph","error":"LDAP Result Code 200 \"Network Error\": dial tcp [::1]:9235: connect: connection refused","time":"2023-01-19T20:45:41.883882334Z","message":"could not get ldap Connection"}
{"level":"error","service":"graph","error":"LDAP Result Code 200 \"Network Error\": dial tcp [::1]:9235: connect: connection refused","time":"2023-01-19T20:45:41.88454575Z","message":"autoconnect could not get ldap Connection"}
```

**Comment by rhafer** [comment]
> With the following logs in ocis container:
> 
> ```
> {"level":"error","service":"graph","error":"LDAP Result Code 200 \"Network Error\": dial tcp [::1]:9235: connect: connection refused","time":"2023-01-19T20:45:41.883882334Z","message":"could not get ldap Connection"}
> {"level":"error","service":"graph","error":"LDAP Result Code 200 \"Network Error\": dial tcp [::1]:9235: connect: connection refused","time":"2023-01-19T20:45:41.88454575Z","message":"autoconnect could not get ldap Connection"}
> ```

I think you can safely ignore this error.  (Unless it appears repeatedly in your logs). This error shows up sometimes during startup when the graph service (or some other service) tries to contact the internal LDAP service before that is fully up. (It will re-try automatically). 

Looking at the screen shot you provided I am not entirely sure what's wrong in your case. But it looks as if there is some issue with resolving hostnames. Seems the webui fails to download some resources from the server, because it can't resolve the hostname correctly. Are you sure the DNS setup on your test machines is correct? (Can you e.g. resolve the `OCIS_URL` correctly?

**Comment by big1tasty** [comment]
Thank you very much! And sorry for opening a Issue because of my stupid mistake.
In fact i made a simple typo and switched two letters in the `OCIS_URL` which i could not see until i looked really closely.
