### ISSUE TITLE
Renaming user in LDAP fails 

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#5581]
## Describe the bug

While calling the graph api editUser and changing the username, the following error stack will be displayed 

```
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=115 SRCH attr=displayName owncloudUUID mail uid sn givenname
ocis_ldap-ldap-server-1   | 63ecf1e8 <= mdb_equality_candidates: (ownCloudUUID) not indexed
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=115 SEARCH RESULT tag=101 err=0 nentries=1 text=
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=116 SRCH base="dc=owncloud,dc=com" scope=2 deref=0 filter="(&(objectClass=ownCloud)(objectClass=groupOfNames)(member=uid=zweistein,ou=users,dc=owncloud,dc=com))"
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=116 SRCH attr=cn owncloudUUID
ocis_ldap-ldap-server-1   | 63ecf1e8 <= mdb_equality_candidates: (member) not indexed
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=116 SEARCH RESULT tag=101 err=0 nentries=4 text=
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=117 MODRDN dn="uid=zweiStein,ou=users,dc=owncloud,dc=com"
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=117 RESULT tag=109 err=0 text=
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=118 SRCH base="uid=dreisteib,dc=owncloud,dc=com" scope=0 deref=0 filter="(&(objectClass=inetOrgPerson)(objectClass=ownCloud))"
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=118 SRCH attr=displayName owncloudUUID mail uid sn givenname
ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=118 SEARCH RESULT tag=101 err=32 nentries=0 text=
```

## Steps to reproduce

1.
2.
3.

## Actual behavior
A clear and concise description of what happened.

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by rhafer** [comment]
> ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=117 MODRDN dn="uid=zweiStein,ou=users,dc=owncloud,dc=com"
> ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=117 RESULT tag=109 err=0 text=

Updating the user name in LDAP actually worked :point_up_2: 

> ocis_ldap-ldap-server-1   | 63ecf1e8 conn=1006 op=118 SRCH base="uid=dreisteib,dc=owncloud,dc=com" scope=0 deref=0 filter="(&(objectClass=inetOrgPerson)(objectClass=ownCloud))"

But the backend is trying to re-read the updated user back using the wrong basedn (`dc=owncloud,dc=com` vs `ou=users,dc=owncloud,dc=com`). This is because we're constructing the User DN in a wrong way: https://github.com/owncloud/ocis/blob/master/services/graph/pkg/identity/ldap.go#L496

We can't guarantee that the users are alway directly  children of the configured `userBaseDN`. They can be in the tree somewhere below that baseDN.

So for reading back the renamed user we'd need to construct the new DN from the old DN by splitting of the first part. I think the most reliable way for that would be to utilize `dn = goldap.ParseDN(oldDN)`  -> replace the  first element  from dn.RDN with the new RDN ->  and convert back to string with dn.String()  -> use that DN for looking up the user.

@ainmosni if you need help with that. Just ping.
