### ISSUE TITLE
Creating the group with name `=` only gives `500` 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#5970]
## Describe the bug

Creating the group with name `=` only gives `500` 

## Steps to reproduce

1. create a group with name `=` only 
```
curl -XPOST "https://localhost:9200/graph/v1.0/groups" -d'{"displayName":"="}' -uadmin:admin -vk 
```

## Expected behavior
Either the group gets created (as we can create groups with just `!` as name or other special chars)  or there's some appropriate error code saying it's not allowed. 

## Actual behavior
It gives `500` 
```bash
< HTTP/1.1 500 Internal Server Error
< Content-Length: 218
< Content-Type: application/json; charset=utf-8
< Date: Thu, 30 Mar 2023 10:35:51 GMT
< X-Graph-Version: 3.0.0-alpha.1+182c375d2
< 
{"error":{"code":"generalException","innererror":{"date":"2023-03-30T10:35:51Z","request-id":"swikriti-OptiPlex-3070/Kr9yv4Ag9A-000324"},"message":"LDAP Result Code 2 \"Protocol Error\": incomplete type, value pair"}}

```
## Setup
OCIS_COMMIT_ID= 182c375d2c46d7985339a0d9e1de8bd5cd89cd03

**Comment by SwikritiT** [comment]
Note that issues https://github.com/owncloud/ocis/issues/5966 https://github.com/owncloud/ocis/issues/5968 https://github.com/owncloud/ocis/issues/5969 might be related. I created them separately as behaviours weren't the same

**Comment by kobergj** [comment]
Also related to the same issue in the `ldap` package. It is definitely not expecting `=` in names as it reacts inconsistent.
- If creating a group `=` it will return an error
- If creating a group `grp=` it will not return an error, but screw up consecutive renames
- If updating a group to `grp=` it will panic

This is because it expects `=` as separator for key-value pairs, which is fine. However it does validate very inconsistently. It should not panic and should consistently return errors if key-value pairs are not complete

For now I would suggest to forbid `=` in group names as done here: https://github.com/owncloud/ocis/pull/5972

closing this for now
