### ISSUE TITLE
Admin user tries to change his/her own role gives 500 status code

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#6037]
## Describe the bug
When an Admin user tries to change his/her own role gives a 500 status code, with a response body containing the message 403 Forbidden.

## Steps to reproduce

1. Create `user1`
2. Grant role `Admin` to `user1`
3. Change `user1` role to `newRole`

Endpoints:

POST: /graph/v1.0/users/`user-id`/appRoleAssignments/
```console
curl -kv -XPOST -uuser1:1234 https://host.docker.internal:9200/graph/v1.0/users/37130879-7646-44be-9e6c-4ea67c2b7c50/appRoleAssignments \
-H 'Content-Type: application/json' \
-d '{"appRoleId": "2aadd357-682c-406b-8874-293091995fdd","principalId": "37130879-7646-44be-9e6c-4ea67c2b7c50","principalType": "User","resourceDisplayName": "ownCloud Infinite Scale","resourceId": "some-graph-app-id"}'
```

## Expected behavior
HTTP/1.1 403 Forbidden

## Actual behavior
HTTP/1.1 500 Internal Server Error

```json
{
    "error": {
        "code": "generalException",
        "innererror": {
            "date": "2023-04-12T11:18:35Z",
            "request-id": "c612df5afef9/cBddd5avYf-014460"
        },
        "message": "{\"id\":\"ocis-settings\",\"code\":403,\"detail\":\"Changing own role assignment forbidden\",\"status\":\"Forbidden\"}"
    }
}
```

**Comment by micbar** [comment]
We should fix the error code during the test writing.

**Comment by ScharfViktor** [comment]
PR https://github.com/owncloud/ocis/pull/6030 is blocked due to problems: #6037 #6035

status code 500, but response message `"{\"id\":\"ocis-settings\",\"code\":403,\"detail\":\"Changing own role assignment forbidden\",\"status\":\"Forbidden\"}"`



![Screenshot 2023-05-05 at 09 24 01](https://user-images.githubusercontent.com/84779829/236399189-af789a3c-09af-4e60-93ca-93c2fbda92d1.png)
