### ISSUE TITLE
Ocis vs ldap. No notifications to user

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6184]
https://github.com/owncloud/ocis/issues/6105#issuecomment-1525596560

ocis against ldap using https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_ldap/docker-compose.yml

- admin shares file to einstein
- einstein logs in

Expect: einstein has notification

Actual: No notification. 502 error
![Screenshot 2023-04-27 at 14 22 17](https://user-images.githubusercontent.com/84779829/235090393-9eb5650a-cff5-425a-a7ab-8c0b2895f43e.png)

log: 
```
{"level":"error","service":"proxy","error":"not found","service":"com.owncloud.userlog.userlog","time":"2023-04-27T12:17:29.423137876Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/router/router.go:139","message":"could not select service from the registry"}


2023/04/27 12:17:29 http: proxy error: unsupported protocol scheme ""

{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"9651f55d-9ade-4abc-b5cc-2359cd6a079e","remote-addr":"172.29.0.1","method":"GET","status":502,"path":"/ocs/v2.php/apps/notifications/api/v1/notifications","duration":10.633583,"bytes":0,"time":"2023-04-27T12:17:29.423246334Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}

```

cc @kobergj

**Comment by rhafer** [comment]
Just stumbled over this. I think this is because the ocis_ldap deployment uses OCIS_RUN_SERVICES (https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_ldap/docker-compose.yml#LL81C7-L81C24) to avoid starting the "idm" service. However, the recently introduced  `userlog` service is not included in that list. 

I think we should remove OCIS_RUN_SERVICES from the example and use `OCIS_EXCLUDE_RUN_SERVICES=idm` instead. Makes things more obivous.
