### ISSUE TITLE
(un-)sharing spaces with large groups is slow

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#6298]
sharing a space with a group that has 2500 users  takes ~2sec, unsharing as well...

![image](https://github.com/owncloud/ocis/assets/956847/66554f09-dbc7-422c-bccc-732396fed3c1)

It seems in this case the GroupAPI/GetGroupByClaim is slow ...

The performance impacts load tests in large deployments.

**Comment by lemanschik** [comment]
Its just a Idea but maybe graphql is not the right Implementation method for such kind of services. 

In Scenarios where the CDN Edge and the backend entrypoint is not on the same server you can forget it in total as there will happen multiple streams from the CDN edge to the backend entrypoint.

Example storys to verify that. 

- How Amazon Prime migrated away from Serverless and Microservices to Monolith and saved over 90% server cost and raised performance
- See Vercels new offer to store functions directly on cloudflare so that Vercel (NextJS) and so on.

I design cloud Platforms of Multi TB Size and did even larger Scales.

For OpenCloud (Distributed Filesystem with access management ACL on top) 
The most performant clever thing would be believe it a NodeJS Backend without any Database.

The Only Database that exists is a Single Json file that you can even rotate to be save from storage issues. 

v8 is hell fast when reading json
v8 is hell fast when manipulating json
json stored inside a array gives you already a key value store implementation (hashMap)

the internal format for files no matter what backend you will use as soon as it goes to the browser will be UInt16Array anyway because that's what Javascript ECMAScript uses internal its a UTF-8 Based language a super set of JSON with added computation.

**Comment by butonic** [comment]
https://github.com/owncloud/ocis/pull/6303 was merged, closing
