### ISSUE TITLE
wrong notification. User is notified even if share doesn't create

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6368]
related #6197

ownCloud 
-- | 
3.0.0-rc.4+c08439f23
7.0.0-rc.37

ocis against wopi using https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml
or open [ocis.ocis-wopi.released.owncloud.works](https://ocis.ocis-wopi.released.owncloud.works/)

Steps: 

- share, delete or edit opening in the onlyOffice file to user einstein 

Actual: share didn't create/edit/deleted but einstein gets notification

https://github.com/owncloud/ocis/assets/84779829/c2a39f44-b327-46ca-b89a-901ca726118e

Expected: no notification for einstein

**Comment by rhafer** [comment]
Hm, this is a tricky one. The gateway creates user shares in a two step process. First is issues a CreateShare request to the shareprovider and second is issues a AddGrant request to the storage provided.

When a file is locked (e.g. because it is opened in onlyoffice) CreateShare request succeeds and  the AddGrant request fails. The ShareCreated event (which results the user notification) is however already fired by the shareprovider after the CreateShare request succeeded :cry:

Ideally we would fire the event only after both requests succeeded. This isn't easily possible as the shareprovider (which is sending the event doesn't about the additional AddGrant call). I am still investigating possible solutions ...

**Comment by micbar** [comment]
@tbsbdr Can you qualify? P3 or P2?

**Comment by tbsbdr** [comment]
P3
what happeny if you click on the notification (via the bell)?

**Comment by ScharfViktor** [comment]
> P3 what happeny if you click on the notification (via the bell)?

Nothing terrible, no crashes no error message. The user just can't find his resource


https://github.com/owncloud/ocis/assets/84779829/517402eb-42cb-4927-8af4-4b0f2a015f9b

**Comment by micbar** [comment]
@kobergj @aduffeck we should try to allow that behavior, if possible.

currently it is a „no go“ because we need to write the new metadata to the mpk file when the office editor closes before we can write the grant.

How would normal file systems handle that? Can you add acls to a file that is locked? I doubt that.

If we allow that, we would create the possibility that people also remove exactly the share which is needed to store the outcome of the editing session which would cause data loss.

**Comment by 2403905** [comment]
@micbar Could we send a notification only if the `userlog`  got the sequence of two events `CreateShare` and `AddGrant`?

**Comment by micbar** [comment]
@butonic @rhafer @kobergj @aduffeck 

IMHO we should really invest time to make sharing and setting the grant of a locked file possible. This would close many Tickets where users are confused.

From a product POV it is also very hard to add more people to an exisiting WebOffice Session. You would need to directly contact all participants and ask them to leave the session 🙈 That is not easy.

**Comment by micbar** [comment]
@dragonchaser and @aduffeck will connect on the Draft PR.

@butonic can you please share your opinion on this?

**Comment by aduffeck** [comment]
draft PR with passing CI: https://github.com/cs3org/reva/pull/4464

**Comment by butonic** [comment]
We don't change the mtime, tmtime or etag when modifying grants on a file: https://github.com/cs3org/reva/pull/4464#issuecomment-1903959817
We can declare `oc:permissions`and `oc:share-id` as unlockable to be RFC compliant: https://github.com/cs3org/reva/pull/4464#issuecomment-1904125954

No objections to allow modifing shares while a file is locked.

**Comment by dragonchaser** [comment]
fixed with #8264
