### ISSUE TITLE
Download as archive produces corrupt archive if over limit

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6555]
## Describe the bug

The default archive max size is set to 1GiB. If one downloads a folder as archive, that is bigger that that, the archive will be capped at that size and is corrupt / can not be opened.

## Steps to reproduce

1. upload files in a folder, that produce an archive > 1GiB
2. download folder as archive

## Expected behavior
see an error message, that the archiving process failed because of the size limit.
have no archive downloaded.

## Actual behavior
archive downloads happily without any error message, but one cannot open it.

## Setup

oCIS 3.1.0-next.2 in Kubernetes with the oCIS Helm Chart

**Comment by kulmann** [comment]
web master had a change so that the archive download button will be disabled (and limitation explained via tooltip). But I don't think that that's sufficient. The archive should at least not be corrupted... or rejected in the first place.

**Comment by kulmann** [comment]
> > web master had a change so that the archive download button will be disabled (and limitation explained via tooltip). But I don't think that that's sufficient. The archive should at least not be corrupted... or rejected in the first place.
> 
> How can Web do that? My understanding is that this is the maximum size of the archive, so AFTER compression.

Announced to clients in capability. If that's not the uncompressed size I don't know why it would ever be announced as a capability.

**Comment by kulmann** [comment]
... and how would the information about a max compressed archive size be useful to the archiver service? "throw it away if compressed archive exceeds 1GiB"? That doesn't sound very useful. 😜

**Comment by kobergj** [comment]
Server currently only counts uncompressed bytes when creating the archive. So your 1.000001 GB folder will fail.

There is a bug in the server implementation (it doesn't close the writer) which probably causes the archive to be corrupted. It is intended to be valid but not containing all files.

Is this still the desired behaviour? Then I'll just fix the bug. Otherwise I can change behaviour as needed

**Comment by hendrychjan** [comment]
Hi, I have a followup question - is it possible to increase the limit of max archive size? Suppose someone shared a folder with a thousand images to me, and I want to download it. I think just selecting the folder and downloading it makes sense, rather than clicking up a thousand images and downloading them one by one.
Thanks for the reply :)

**Comment by wkloucek** [comment]
> Hi, I have a followup question - is it possible to increase the limit of max archive size? Suppose someone shared a folder with a thousand images to me, and I want to download it. I think just selecting the folder and downloading it makes sense, rather than clicking up a thousand images and downloading them one by one. Thanks for the reply :)

please have a look at FRONTEND_ARCHIVER_MAX_SIZE and FRONTEND_ARCHIVER_MAX_NUM_FILES in https://doc.owncloud.com/ocis/7.2/deployment/services/s-list/frontend.html
