### ISSUE TITLE
auth-bearer logs in the gateway service

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#6692]
## Describe the bug

I see following logs all over the place in the gateway service:

```
{"level":"error","service":"gateway","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"internal error: gateway: error finding an auth provider for type: bearer","type":"bearer","time":"2023-07-03t07:36:19.985383823Z","line":"github.com/cs3org/reva/v2@v2.14.1-0.20230616125400-b30fdde17262/internal/grpc/services/gateway/authprovider.go:47","message":"error getting auth provider client"}
```

From my understanding, we don't even use the auth-bearer service in oCIS (https://github.com/owncloud/ocis/issues/4701). This is also why the oCIS Helm Chart doesn't even start it.

## Steps to reproduce

Run oCIS 3.1.0-next.2 in Kubernetes with the oCIS Helm Chart

## Expected behavior
See only logging that makes sense

## Actual behavior
See a lot of logging referencing the auth-bearer service

**Comment by micbar** [comment]
This needs a severity and a priority.

**Comment by rhafer** [comment]
> From my understanding, we don't even use the auth-bearer service in oCIS (#4701). This is also why the oCIS Helm Chart doesn't even start it.

That's true. Some other service is still  trying to Authenticate with that provider. Not sure yet which one.

**Comment by rhafer** [comment]
> Not sure yet which one.

It's the `frontend` service via http auth middleware/interceptor of reva. And I am struggling a bit how to correctly solve it. Bascially it happens because:

- we configure the auth-interceptor to allow `Bearer` auth (I guess mainly to return a useful WWW-Authenticate Header with 401 Reply). That's happening here: https://github.com/owncloud/ocis/blob/master/services/frontend/pkg/revaconfig/config.go#L113
- additionally the proxy does not strip off the ` Authorization: Bearer` Header from the request it forwards to the reva services

When a client (e.g. web) does a request on an unprotected endpoint (e.g. `/ocs/v1.php/cloud/capabilities`):
1.the proxy will not request a revatoken for it (as it is marked unprotected), but the request still contains the `Authorization: Bearer` Header with a valid OIDC access token.
2.  The proxy service will forward that request to the `frontend` service. Including the `Authorization: Bearer`
3. As there is no revatoken in the request the auth-middleware will try to verify the Bearer token. Which fails because we don't run the auth-bearer service.

There is a couple of possible fixes, which we should implement I think:
- Don't configure the reva http auth middleware to allow `bearer` auth. Currently it's not possible to configure an empty list for `credential_chain` (it would default to `bearer, basic` then. But in our case it's the probably the right thing to do as all the "external" authentication is handled in the proxy currently. (Downside: we wouldn't return the WWW-Authenticate Headers anymore for request that require authentication, but ideally those would be added by the proxy anyways)
- Strip the `Authorization:` Header from the request in the proxy, they're currently of no real use for the backend service. All of the should be authorized using the reva-token.
- Have the auth middleware skip the Authenticate step for endpoints marked as unprotected.

**Comment by rhafer** [comment]
> * Have the auth middleware skip the Authenticate step for endpoints marked as unprotected.

This change explicitly remove skipping the Authenticate step for unprotected endpoints: https://github.com/cs3org/reva/pull/2698/commits/231d325bfb5c16a82b7b92e6803566c8c552148d . It does of course not mention why. \*sigh\* :sob: 

Does e.g. the capabilities endpoint return different things whether the request is Authenticated or not? (I don't think so)

**Comment by micbar** [comment]
@rhafer Thank you for the good research.

> Does e.g. the capabilities endpoint return different things whether the request is Authenticated or not? (I don't think so)

That is not the case.
