### ISSUE TITLE
Sharing to a user does not work

### ISSUE THREAD

**Issue by madsi1m** [owncloud/ocis#68]
When trying to share a folder to another user in Phoenix/Reva
![image](https://user-images.githubusercontent.com/11512591/70680990-f3b87380-1ced-11ea-80b9-b0a6502b63db.png)

Nothing interesting in container logs, or in javascript console logs

**Comment by C0rby** [comment]
The only way I could reproduce the message was following:

- Add a collaborator to a folder
- Switch the view e.g. to Links
- Switch back to collaborators of that folder
- See that there are no collaborators shown
- Add same collaborator as in the first step
- Get error message

The reason why the collaborator is not shown is that when the storage provider wants to list all the collaborators it will first stat the folder/file. For that it wants to get the file/folder path from redis but when there is no redis instance running it will get a connection error and fail with the message "error stating {filepath}".

@butonic, how should we continue with this?

**Comment by butonic** [comment]
I can confirm @C0rby and shed some more light into what is happening.

When einstein is sharing something with marie things work properly from his perspective, until reva is restarted. reva currently caches the *shared with me* and *shared with others* only in memory: https://github.com/cs3org/reva/blob/master/pkg/share/manager/memory/memory.go
- [ ] we need to implement a more persistent cache like redis, or refill the in memory cache during startup / periodically

from maries perspective three things are not yet working:
1. she does not see the share in her *shared with me* list. This is a bug and IIAC @refs knows what to do about it.
2. she has no way of accepting and mounting a share, but I don't know how far phoenix is in that regard. maybe @LukasHirt can chime in.
3. she does not yet see the incoming share in her home storage. The idea is that the storage provider can store a reference, which works like a mount point. the gateway, however, will replace that reference with the actual file metadata from the referenced storage. clients using the gateway will never see the references.
  - [ ] this still needs to be implemented in reva AFAICT, but @labkode did some work on getting home storages, and I need to catch up on how things changed.

**Comment by madsi1m** [comment]
why not mariadb for shares? (just asking)

**Comment by butonic** [comment]
@madsi1m most support cases we see are caused by inconsistencies between the oc_filecache in the database (which is not a cache, but an index which is used to attach share information to files) and the metadata in the filesystem. With ocis/reva we will delegate storing additional metadata, especially share information to the storage providers who are supposed to make use of all storage capabilities. EOS for example can propagate etags and calculate tree sizes on its own. but it still cannot store share expiry. That is something the storage provider can implement in a way that best fits the storage.

For EOS Shares are implemented as ACLs. Which makes some operations slow, eg finding all ACLs to answer the "shared with me" question. Posix filesystems are not built to answer that question quickly or efficiently. The solution of choice is to build a dedicated read model to answer these queries efficiently.

The question is how they will be updated? Currently, the gateway will do that: it will send the grant request to the storage and also update the share manager (which implements the read model). With the switch to golang we can properly implement eventual consistency for the read models.

The idea is that all the read models can be rebuilt from scratch and are treated like true caches. Which brings us to your question: why not mariadb for shares? Currently, we only store the shares read model in memory and we need a way to persist or reconstruct that when restarting reva/ocis. The owncloud storage driver already requires redis to look up paths for fileids.
I'd reuse that, because
1. it fits the purpose of a cached read model. At least better than mariadb.
2. redis could be exchanged for [quarkdb](https://github.com/gbitzes/QuarkDB) which is already recommendted for EOS AFAIK
3. it does not add a new dependency.

But I am open to arguments. I am eg. looking into etcd, which we might embed into ocis ... or at least use the [go micro store interface](https://github.com/micro/go-micro/tree/master/store) which can be used for multiple implementations: cockroachdb, etcd, cloudflare or via [go micro plugins](https://github.com/micro/go-plugins/tree/master/store): consul, memcached or redis.

**Comment by LukasHirt** [comment]
> she has no way of accepting and mounting a share, but I don't know how far phoenix is in that regard

If this is in sense of pending shares then Phoenix is capable of accepting/rejecting shares via notifications.

https://github.com/owncloud/phoenix/blob/6f62fcd04160e75c30a162f0551edbc7626ee670/src/components/Notifications.vue#L59

**Comment by labkode** [comment]
@butonic very nice summary of the sharing model. For point 3. is on me, I'm creating references in EOS and mounting them in the shares, the PR is still in Draft, next week we'll have enough time to hack that and make it working.

Redis is a very good option to act as a cache however for single binary deployments it requires a separate service.

I want to explore the idea of using some embedded database and create one DB per user. Badger or Bolt would be a nice match however they cannot be used from multi-process environments I would like to find something out there.
