### ISSUE TITLE
Providing folder as destination while move/copy file destroy folder data

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6983]
## Describe the bug
a file(say testfile.txt) is copied over the top of an existing folder(say FOLDER), which overwrites the folder. The folder changes into the file and the name is of the folder(FOLDER)

## Question
- Is It Valid to Specify a Folder as the Destination?

## Steps to reproduce

1. create folder `New Folder` 
2. create file `hello.txt` and `New Folder/example.gif`
3. move file `hello.txt` to `New Folder` 
```
curl -XMOVE 'https://localhost:9200/remote.php/dav/spaces/aafeb67a-4a2a-483a-a91f-f475a8a032f2%244c510ada-c86b-4815-8820-42cdf82c3d51/hello.txt' \
-H 'Destination: https://localhost:9200/remote.php/dav/spaces/aafeb67a-4a2a-483a-a91f-f475a8a032f2%244c510ada-c86b-4815-8820-42cdf82c3d51/New%20folder/' \
```

## Expected behavior
- behavior should be similar to this issue https://github.com/owncloud/ocis/issues/6739

## Actual behavior
- status code `204 No content`. File renamed into `New folder`. The existing folder `New folder` moved to trashbin

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS = 3.1.0-rc.1+712d98e0a2
```

</p>
</details>

**Comment by saw-jan** [comment]
This should be the expected behavior.
CC @2403905

**Comment by 2403905** [comment]
@kobergj @butonic We have a bunch of similar issues where the source is a file and the destination is a folder when copying/moving via the API.
What is an expected behavior should be here?
There are only examples in  a webdav spec where the resource and destination have the same type (collection or non-collection)
[http://www.webdav.org/specs/rfc4918.html#n-copy-for-non-collection-resources](http://www.webdav.org/specs/rfc4918.html#n-copy-for-non-collection-resources)

**Comment by 2403905** [comment]
> > status code 204 No content. File renamed into New folder. The existing folder New folder moved to trashbin
> 
> This should be the expected behavior, right? CC @2403905 @ScharfViktor

This is an expected behavior

**Comment by saw-jan** [comment]
@2403905 Please, you may close the issue if the behavior is expected
