### ISSUE TITLE
Blank page at first launch

### ISSUE THREAD

**Issue by gsebil08** [owncloud/ocis#7100]
## Describe the bug

Blank page at first launch of `ocis` 3.0.0

With failed request `https://localhost:9200/.well-known/openid-configuration`:
<img width="954" alt="image" src="https://github.com/owncloud/ocis/assets/45454460/7eb71565-7384-4dc0-8fb6-66ebe00ee297">

## Steps to reproduce

1. fresh new rpi 4 with rpsbian 64
2. Setup etcd
3. install `ocis` 3.0.0 via official doc

## Expected behavior

Access launching page

## Actual behavior

Blank page loading for ever + failed `https://localhost:9200/.well-known/openid-configuration` request

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
export PROXY_TLS=false
export MICRO_REGISTRY=etcd
```

Command to launch `ocis`:

```console
OCIS_INSECURE=true IDM_CREATE_DEMO_USERS=true PROXY_HTTP_ADDR=0.0.0.0:9200 OCIS_URL=https://localhost:9200 ocis server
```

</p>
</details>

## Additional context

Exact same behavior on `ocis` 2.0.0. I think it may be due to HTTPS/TLS but I feel like I have deactivated them for now...

**Comment by rhafer** [comment]
You've set: `PROXY_TLS=false` and `OCIS_URL=https://localhost:9200`

This can only work if you're using a TLS terminating reverse proxy in front of your ocis instance. If you want to use ocis without a reverse proxy you need `PROXY_TLS=true` (the default). For details see also: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#special-settings

**Comment by gsebil08** [comment]
I am not sure to understand your answer.

The `ocis` server is running on a machine on my local network. I want to access it from a second machine.

Two questions:

1. How can I do it by disabling TLS?
2. How can I do it by enabling TLS?

So far, if I strictly followed your documentation, I lead to the exact same blank page I already sent (which is the error on distant machine accessing to `ocis` machine).

**Comment by rhafer** [comment]
> Two questions:
> 
>     1. How can I do it by disabling TLS?

When using the built-in IDP you can't run completely without TLS. For the reasons described in the documentation linked above ("because the embedded libreConnect shipped with the IDP service has a hard check if the connection is on TLS and uses the HTTPS protocol. If this mismatches, an error will be logged and no connection from the client can be established"). 
Your only option, if you want to run ocis without TLS is to put a reverse proxy (like e.g. traefik) in front of ocis and let that proxy handle the TLS termination. But your clients will still need to use https to access that reverse proxy.

>     2. How can I do it by enabling TLS?
> 
> So far, if I strictly followed your documentation, I lead to the exact same blank page I already sent (which is the error on distant machine accessing to `ocis` machine).

I suspect you still had the `OCIS_URL` setting pointing to `localhost`? That will only work if you access ocis only from localhost. For accessing it remotely. You need to set `OCIS_URL` to the hostname and port via which ocis will be reachable from the external machine. (Additionally ocis must be able to reach itself via that hostname and port).

BTW, I'd suggest to take this to central.owncloud.org, which IMO is more suitable for discussing configuration issues. If this turns out to be a bug in the code or that documentation needs improvement we can still open new issues in github.

**Comment by gsebil08** [comment]
Thanks @rhafer , working great by modifying the `OCIS_URL`. I didn't understand from reading the docs, that this uri needs to be the reachable from outside.
