### ISSUE TITLE
Admin regaining control of a Space

### ISSUE THREAD

**Issue by J-Light** [owncloud/ocis#7265]
## Describe the bug
We've got a setup with multiple users who have access to both individual storage and shared spaces. After updating from version 2 to 3, we lost the ability to see one particular space, although we can still see other spaces. When we rolled back to version 2 using a backup, I realized that I don't have administrative control over the issue-affected space and may be the reason for the issue with the upgrade. I can look at files, upload new ones and so on in this space, but I can't alter the member settings.

How do I regain manager membership to this space. 

## Steps to reproduce
Unable to reproduce and not sure what caused this situation. 

## Expected behavior
A administrator should always be able to change Mangers and access to spaces. 

## Actual behavior
The global admin is locked out of one of the spaces. 

## Setup
Its running as a docker service.

**Comment by kobergj** [comment]
When you click on the members tab of the space you can find out who is manager of it. You need to ask one of the managers to promote you to manager. This is currently the only way to regain manager access. This is because of security reasons: We do not want "some" user to take control over a space with existing data.

Of course you could also download all files of this space and re-upload it to a new space as a workaround.

**Comment by mrblacyk** [comment]
Hey @kobergj ,

I actually also hit this problem. I have the latest published helm chart applied.

My IDM service certificate expired after a year, I regenerated it, deleted IDM and IDP pods, recreated them, and had to re-create the users because of it. Those spaces weren't reassigned to the users of the same username. From admin view, I now see spaces with the data on it, but there is *no* manager of such space.

Unfortunately, spaces were created from the user view, and not the admin view. I will be creating spaces from the admin view from now on, so in case users are wiped, spaces are not lost.

Is there maybe some CLI command for regaining access to such spaces? 

Thanks in advance
