### ISSUE TITLE
[Issue] Incredible slow upload speed with many small files

### ISSUE THREAD

**Issue by thrhgh** [owncloud/ocis#7559]
Hi together.

First of all thank you very much for this absolutely great product! I just have one issue: If I upload many small files, it is incredible slow (see screenshot). Syncing large files is no issue and it works like a charm.
![ocis](https://github.com/owncloud/ocis/assets/69689551/af6966cb-1dd8-4e8c-8c84-2d6804e8122f)

My setup:
Server: Owncloud ocis via docker and use caddy v2 as a reverse proxy. The system is running debian 12 and the filesystem is xfs for the storage path. This composer file:

> 
> ocis:
>     container_name: ocis
>     image: owncloud/ocis:latest
>     environment:
>       OCIS_INSECURE: "false"
>       PROXY_TLS: "false"
>       PROXY_HTTP_ADDR: "removed:9200"
>       PROXY_USER_OIDC_CLAIM: "preferred_username"
>       PROXY_USER_CS3_CLAIM: "username"
>       PROXY_ENABLE_BASIC_AUTH: "true"
>       OCIS_URL: "removed"
>       STORAGE_USERS_OCIS_ASYNC_UPLOADS: "true"
>       PROXY_OIDC_USERINFO_CACHE_TTL: 1800000000000
>       OCIS_LOG_LEVEL: info
>     volumes:
>       - ./ocis/ocis.yaml:/etc/ocis/ocis.yaml
>       - /mnt/hdd/Drive1:/var/lib/ocis
>     expose:
>       - 9200
>     restart: unless-stopped
>     logging:
>       driver: local
>     networks:
>       static-network:
>         ipv4_address: removed
> 

On my Desktop machine I use Fedora 39 with Owncloud Client Version 4.2.

This is an example output of my log files of the Desktop App:

`
23-10-22 18:26:33:426 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 1 rows.
23-10-22 18:26:33:426 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec: "DELETE FROM uploadinfo WHERE path=?1" Try: 0
23-10-22 18:26:33:426 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
23-10-22 18:26:33:426 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "upload file start" and starting new transaction
23-10-22 18:26:33:426 [ info sync.propagator ]:	Completed propagation of "FILEPATH" by OCC::PropagateUploadFileTUS(0x5624d2025170) with status OCC::SyncFileItem::Success
23-10-22 18:26:33:426 [ debug sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotItemCompleted ]:	Item completed "FILEPATH" OCC::SyncFileItem::Success SyncInstruction(CSYNC_INSTRUCTION_NEW)
23-10-22 18:26:33:426 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job finished OCC::SimpleNetworkJob(OCC::Account("REMOVED"), "REMOVED", "POST", Original-Request-ID: "REMOVED")
23-10-22 18:26:33:426 [ debug sync.propagator ]	[ OCC::OwncloudPropagator::scheduleNextJobImpl ]:	Can pump in another request! activeJobs = 5
23-10-22 18:26:33:427 [ info sync.propagator ]:	Starting SyncInstruction(CSYNC_INSTRUCTION_NEW) propagation of "FILEPATH" by OCC::PropagateUploadFileTUS(0x5624d20693a0)
`

Anyone is facing a similar issue or could find a solution to this?

**Comment by rhafer** [comment]
@thrhgh When you say "small files". How small is that? Is it just a couple of bytes or several kilobytes per file?

Also to you see high CPU or memory usage of the ocis process? Or is it just busy with I/O?

**Comment by thrhgh** [comment]
@rhafer Thanks for your reply! Server load is quite load as well as my laptop CPU so I don't think this is the issue.

The files range from a few bytes to a few kilobytes. On average, they are <20kb in size.

Any ideas how to improve on this?

**Comment by rhafer** [comment]
> Any ideas how to improve on this?

That's really hard to say with the available information. Also I am not exactly able to reproduce the behavior you're seeing.
Uploading a directory with 100 subdirectories each of which containing 1000 20kB files, takes about 10-15 min on my test system. But that is using an SSD for the ocis storage and I had the client running on the same host. So there is basically no network latency involved.

Trying the same with an ocis running on a separate machine (a pretty slow one) in the same LAN using a (slowish) harddisk instead of ssd already increases the time to a couple of hours, but it's still far quicker that what you're seeing.

What kind of storage are you using for you ocis system? 
What is the network latency between your client and the server. It might have an impact as well, especially when uploading small files.

If I/O really is the bottleneck. You might want to try out the `async` propagator. That could reduce the I/O during upload a bit. It can be enabled by settting `STORAGE_USERS_OCIS_PROPAGATOR=async` and configuring  a delay  (in seconds) for how often to actually trigger the propagation via `STORAGE_USERS_ASYNC_PROPAGATOR_PROPAGATION_DELAY` (the default is 5,  I'd suggest to go with something like 30 for the start). Please be aware that `STORAGE_USERS_OCIS_PROPAGATOR=async` is still an experimental feature so you should probably first try that on a test system.

**Comment by micbar** [comment]
Closed. Our benchmarks show that everything is fine on local storage, NFS and S3.
