### ISSUE TITLE
[ocis] Mountpoints for pending and declined shares

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#7702]

**Comment by micbar** [comment]
# Description

## User Stories

* > As a client, I want to see all received shares because I need that information for routing and URLs

## Value

Make the New URL feature work

## Acceptance Criteria

- [ ] Mountpoint spaces are always listed in the drives list

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by butonic** [comment]
By definition, neither pending nor declined shares are synced. Consequently they should not be returned in the /drives listing. Definitely not by default! Maybe if the request explicitly requests a certain type ... but I fail to see the reason why any client would need it.

The /me/sharedWithMe endpoint holds all necessary information:
1. for accepted shares a driveItem representing mountpoint. It has a remoteItem property for the shared file or folder.
2. for pening shares a driveItem representing the shared file or folder
3. all drileItems have a parentReference that can contain all necessary metadata (see [itemReference](https://learn.microsoft.com/en-us/graph/api/resources/itemreference?view=graph-rest-1.0)), eg the drive id, type aka the space metadata visible to the recipient.
4. The direct parent driveItem metadata can be left empty if the recipient has no access to it. This might be a deployment specific configuration, eg. some instances might allow access to all resources in a common space or on the shared underlying storage system like EOS.

**Comment by kulmann** [comment]
@tbsbdr @micbar I'd like to suggest that we close this issue as `won't fix`.

Like @butonic mentioned, we will be able to do this properly with the SharingNG share listing. We are not able to incorporate that in the upcoming web `v8.0.0` stable release, because that release is the one that cernbox will use, so it can't make use of SharingNG, yet.

As a result, we would need to accept the web ui behaviour of not being able to navigate into any pending or declined shares as a known bug in web v8.0.0 / ocis v5.0.0. That was never possible, but now with the recent changes to the shared with me page the UI suggests that you can navigate into pending and declined shares, that's why this issue came up in the first place.

The solution proposed in this issue would immediately be useless when we switch over to SharingNG in the web ui.

**Comment by kulmann** [comment]
@JammingBen would it be feasible to disable the router links in the shared with me page for declined and pending shares for the upcoming web v8.0.0?

**Comment by JammingBen** [comment]
> @JammingBen would it be feasible to disable the router links in the shared with me page for declined and pending shares for the upcoming web v8.0.0?

This would be doable without much effort, yes 👍

**Comment by micbar** [comment]
fine for me too.

**Comment by kulmann** [comment]
> > @JammingBen would it be feasible to disable the router links in the shared with me page for declined and pending shares for the upcoming web v8.0.0?
> 
> This would be doable without much effort, yes 👍

Thank you 👍  created https://github.com/owncloud/web/issues/10094 for this
