### ISSUE TITLE
[Feature requests] File Shortcuts 

### ISSUE THREAD

**Issue by HuJK** [owncloud/ocis#8202]
## Is your feature request related to a problem? Please describe.
I'm consistently facing challenges when accessing specific files in my web drive. Navigating through folders to find frequently used files is time-consuming and inefficient.

## Describe the solution you'd like
I would like to propose the implementation of a file shortcut feature in the web drive. This feature should allow users to create shortcuts to specific files, enabling quick access without the need to navigate through multiple folders.

## Describe alternatives you've considered
While marking favorites for folders is an option(although it's not implemented yet, either), it doesn't address the need for direct shortcuts to individual files. A dedicated file shortcut feature would provide a more targeted solution to enhance user productivity.

## Additional context
The absence of a file shortcut feature currently requires users to navigate through a series of folders to locate important files. The introduction of file shortcuts would significantly improve the user experience by enabling quick and direct access to frequently used files.

**Comment by kulmann** [comment]
Hey @HuJK thanks for checking out ocis! We've actually already built that feature end of 2023 and it will be part of the upcoming ocis 5.0.0 release. You could check it out in the latest release candidate if you want to. Happy about feedback! You can find the feature in the "+ New" menu where you create files and folders above the file listing. It's called "Shortcut" and creates .url files. There is a search embedded in the creation form. Just start typing the file names.

**Comment by HuJK** [comment]
That's great!

Just a few questions, can we make the shortcuts be a spcial hidden attribute instead of `.url` filename?  
![image](https://github.com/owncloud/ocis/assets/15907444/64be5228-0632-4999-84be-47b58c72a58d)
Google Drive:
![image](https://github.com/owncloud/ocis/assets/15907444/0462f947-30c1-4b28-8f36-c317305a9401)

### Frontend suggestion:
1. And it's nice if we can create shortcuts from right-click menu directly like google drive:
![image](https://github.com/owncloud/ocis/assets/15907444/79f9d113-301e-42ca-944c-717203d94d79)

2. It's nice if we can add a hint if the origional file has been deleted:
![image](https://github.com/owncloud/ocis/assets/15907444/fb217244-acff-4180-b3c3-e92877dd33d1)

**Comment by kulmann** [comment]
We decided to use the .url file type for both internal and external shortcuts, so it will keep the file ending, sorry. ;-)

I guess that we'll need to analyse those files server side at some point in the future and provide metadata if the file still exists and if the url points to an internal or external target to differentiate them visually in the file list. Since it's a frontend only solution at the moment we don't have the info in a file listing because we would need to fetch metadata individually per url file in the list. That's too expensive and won't happen at the moment.

For the right click context menu I can imagine adding it. Maybe opt in in user preferences, because we try to keep the context menu as small as possible. Already feels a bit crowded and we don't do sub menus yet. Will discuss with the team.

**Comment by micbar** [comment]
Implemented.
