### ISSUE TITLE
[SharingNg] Get shares `sharedByMe` takes a while to get expected response after sharee is deleted

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#8356]
## Describe the bug
When we try to get the shares using `sharedByMe` endpoint after a file is shared (with sharingNg) to the `sharee` and `sharee` is deleted. we get the shares response (initially) but after a while the response is empty (fetched again after 1 min). But when we do the same thing but the file (resource) is shared through `ocs` endpoint then the response is empty(initially) which do not take a while. These difference seems to be odd.

## Steps to reproduce
1. as an `admin` 
2. `admin` create a file `file.txt`
3. create another user `demo` and share `file.txt` with that user (using sharingNg)

curl command for it:

```console
curl -XPOST -k -uadmin:admin 'https://localhost:9200/graph/v1beta1/drives/<drive-id>/items/<item-id>/invite' -H 'Content-Type: application/json' --data-raw '{"recipients":[{"@libre.graph.recipient.type":"user","objectId":"<demo-user-id>"}],"roles":["b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5"]}'
```
4. now delete user `demo`
5. and get the shares shared my `admin` using `sharedByMe` endpoint (sharingNg)

curl command for it:

```console
curl -k -XGET https://localhost:9200/graph/v1beta1/me/drive/sharedByMe -uadmin:admin
```

## Expected behavior
The response should be empty as
```json
"value": []
```

## Actual behavior
But it gives response even if the sharee was deleted.
```json
{
  "value": [
    {
      "eTag": "\"da15e3c9ee9ae9e81dada22e48ba0b26\"",
      "file": {
        "mimeType": "text/plain"
      },
      "id": "292138c9-f891-4e7d-858c-7760d74fec37$dd372d9e-2c58-4960-9044-bafebdef0ed5!eef86039-a532-4aad-89d3-57dafa6718d5",
      "lastModifiedDateTime": "2024-02-02T17:11:47.999692772+05:45",
      "name": "file.txt",
      "parentReference": {
        "driveId": "292138c9-f891-4e7d-858c-7760d74fec37$dd372d9e-2c58-4960-9044-bafebdef0ed5",
        "driveType": "personal",
        "id": "292138c9-f891-4e7d-858c-7760d74fec37$dd372d9e-2c58-4960-9044-bafebdef0ed5!dd372d9e-2c58-4960-9044-bafebdef0ed5",
        "name": "/",
        "path": "/"
      },
      "permissions": [
        {
          "grantedToV2": {
            "user": {
              "displayName": "demo gurung",
              "id": "384e682f-7376-43c9-9e3d-b51ce91245f5"
            }
          },
          "id": "292138c9-f891-4e7d-858c-7760d74fec37:dd372d9e-2c58-4960-9044-bafebdef0ed5:2e684fc6-4617-47c6-9cc1-b74e9e5d495c",
          "roles": [
            "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5"
          ]
        }
      ],
      "size": 0
    }
  ]
}

```

## Conclusion
But after we wait for 1 min (i tried) the response was empty. There was some delay clearing up as we have to wait to get the expected response. But if we do the same thing when we invite share with `ocs` enpoint we get the expected response without waiting.

<details>
<p>

```console
OCIS_XXX=latest mater build
```

</p>
</details>

**Comment by rhafer** [comment]
I think what you're seeing is more or less the expected behavior:

- Deleting a user does not delete any of the received shares of that user
- the sharedByMe endpoint does not return any shares for which it can't resolve the sharee-id to a user or group name. But:
- to limit load on the users and groups service the graph service it using a short lived in memory cache to cache the id to name look ups for some time
- the default ttl for that cache is 1min. It can be configured via the `GRAPH_SPACES_USERS_CACHE_TTL` and `GRAPH_SPACES_GROUPS_CACHE_TTL`. Which my help you if you want to limit the waiting inside the test suite.
- currently there is not invalidation of that cache, when a user is being deleted. (It's also not really possible to do that reliably, especially when users are maintained in some external system)
