### ISSUE TITLE
tests for WOPI protocol

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#8712]
oCIS is offering [WOPI](https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/) as one of its APIs

currently this API is tested using the [wopi-validator](https://github.com/owncloud-ci/wopi-validator) and some very [basic e2e tests](https://github.com/owncloud/web/blob/4f2ac8b7ad2b45a24db973ada928aa89066d9a93/tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature)

These tests don't cover anything related to:
- security
- spaces
- shares
- antivirus
- public links
- versions
- etc.

currently the WOPI service is also re-implemented in #8374

My question is: do we need to have a separate WOPI API test-suite as we have with e.g. WebDAV, TUS, Graph or can be everything tested via unit test and the underlying code-path are tested already with the existing API testsuites?

@jvillafanez @micbar @phil-davis @DeepDiver1975 @dragotin @ScharfViktor ?

**Comment by jvillafanez** [comment]
I think we'll need to come up with our own test suite, maybe in parallel with the wopi validator.

The wopi validator runs a series of actions against the the wopi server. Some of them might be preparation of the actual test, and the validator could skip the test if something goes wrong with the preparation, for example if the target file is missing.
This also means that some actions might be difficult to test through the validator. What happens if you try to lock a file but the file doesn't exist? Pretty sure the validator will skip the test because the `CheckFileInfo` request prior to the `Lock` fails, so we don't know if the wopi server responds correctly to such `Lock` request with a 404 code.

There are also potential race conditions or issues regarding the order of operations that we should ensure they don't break anything (we might need to include code to make testing easier). As far as I know, the wopi validator isn't enough for these kind of issues.

The other big thing is that the `CheckFileInfo` request is tailored to Microsoft so the validator tests pass. Both collabora and onlyoffice include their own set of properties, which I don't think we can test at the moment because the wopi validator will complain.
We'll have to figure out a proper way to support everything (unless we only support microsoft), but we'll need a way to verify that the properties are working, or at least that we send the properties correctly.

**Comment by DeepDiver1975** [comment]
> The other big thing is that the `CheckFileInfo` request is tailored to Microsoft so the validator tests pass. Both collabora and onlyoffice include their own set of properties, which I don't think we can test at the moment because the wopi validator will complain.

We need to see how the validator handles this situation. We might even run into situations where not only different properties are expected but the same properties with different values.

But let's see how this works out.

the wopi validator is open source - we can extend it to our needs. Which might be a possible way to go.
(it is basically xml + c# - happy to help out)

**Comment by individual-it** [comment]
1. most things should be covered by unit + integration tests in Go @jvillafanez @rhafer @2403905 
2. make the e2e UI tests run on the new WOPI service @individual-it @saw-jan 
3. add e2e UI tests to cover the smoke-tests that is done in the release @individual-it @saw-jan 
4. create API tests for `CheckFileInfo` @individual-it @saw-jan 
   - check that all expected values are returned (//TODO add list/documentation link)
   - future: check that env. variables switch the abilities correctly
5. as more functions are added, more wopi validator tests should be switched on @jvillafanez @rhafer @2403905 
6. extend the validator if needed @DeepDiver1975

**Comment by SagarGi** [comment]
> > 3. add e2e UI tests to cover the smoke-tests that is done in the release @individual-it @saw-jan
> 
> Where should we run app-provider e2e tests? Now we run it only web CI. should we include this tests in the ocis CI?

since the app-provider tests is not ran in ocis as of now. May be lets stick to running it only web for now ? @saw-jan @individual-it

**Comment by ScharfViktor** [comment]
> @ScharfViktor since the app-provider tests is not ran in ocis as of now. May be lets stick to running it only web for now ? @saw-jan @individual-it

let's make it only in web for now.

**Comment by saw-jan** [comment]
ℹ️ NOTE: we will wait until the service is stable and there's a deployment example available

**Comment by saw-jan** [comment]
>4. create API tests for `CheckFileInfo`

I see endpoint `<ocis-wopi-server>/wopi/files/{fileid}` that does `CheckFileInfo`.
- Does it return the file-info?
- Will curl request to this endpoint work with ocis basic-auth? (`admin:admin`)

CC @jvillafanez @rhafer @2403905

**Comment by saw-jan** [comment]
Then it looks like it is not possible to have normal API tests for this endpoint. Requires special setup which we don't know yet

**Comment by saw-jan** [comment]
Maybe we can make use of this to get the required token:
https://github.com/owncloud/ocis/blob/f2c50772895a095aebeeceb3ac0a4dac09af8172/.drone.star#L1098-L1109

**Comment by jvillafanez** [comment]
That might work, yes.
```
"echo -n 'http://wopiserver:9300/wopi/files/' > wopisrc", 
"cat open.json | jq .app_url | sed -n -e 's/^.*files%2F//p' | tr -d '\"' >> wopisrc", 
```
I think you can get the wopisrc directly from the `.app_url`, not sure why it's done that way. There might be reasons though.

You'll likely need to send the access token (in the created "accesstoken" file) to the wopi server. Something like `http://wopiserver:9300/wopi/files/0df6a9......?access_token=abcfed...`. The access token is required.
In addition, remember to disable the proof keys verification in the wopi server. This is the easiest solution because we'd need to generate the keys and the proof for each request otherwise.

**Comment by saw-jan** [comment]
```
curl "https://host.docker.internal:9300/wopi/files/{id}?access_token={access_token}"
```
```json
{
  "BaseFileName": "afile.txt",
  "DisablePrint": false,
  "OwnerId": "33653562613161642d313433662d343137622d386265342d3232303863653733623737364068747470733a2f2f686f73742e646f636b65722e696e7465726e616c3a39323030",
  "PostMessageOrigin": "https://localhost:9200",
  "Size": 0,
  "UserCanWrite": true,
  "UserCanNotWriteRelative": false,
  "UserId": "33653562613161642d313433662d343137622d386265342d3232303863653733623737364068747470733a2f2f686f73742e646f636b65722e696e7465726e616c3a39323030",
  "UserFriendlyName": "Admin",
  "EnableOwnerTermination": true,
  "SupportsLocks": true,
  "SupportsRename": true,
  "UserCanRename": true,
  "BreadcrumbDocName": "afile.txt"
}
```

@jvillafanez I made a request with access_token and got this response. Is it the correct one?
Also, I noticed that the `{id}` part can be anything. If I do something like this:
`curl "https://host.docker.internal:9300/wopi/files/abcde?access_token={access_token}"`, I get the response. Is it correct behavior?

**Comment by jvillafanez** [comment]
Yes, that's a good response. It will return the file info from the `CheckFileInfo` method (https://github.com/owncloud/ocis/blob/master/services/collaboration/pkg/connector/fileconnector.go#L1045)
The actual values depend on the view mode and the target WOPI app. Since the target WOPI app is the "FakeOffice", the returned properties will be based on Microsoft (https://github.com/owncloud/ocis/blob/master/services/collaboration/pkg/connector/fileinfo/microsoft.go)
I'm not sure how easy will be to fake Collabora responses. Maybe just changing the app name in the collaboration service is enough.

> Also, I noticed that the {id} part can be anything. If I do something like this:
curl "https://host.docker.internal:9300/wopi/files/abcde?access_token={access_token}", I get the response. Is it correct behavior?

Likely a bug, although I'm not entirely sure.
The file id we're using comes from the access token. We aren't checking the file id in the url for anything, and maybe we should verify it. Basically, the file id from the url and the one from the access token should match.

**Comment by saw-jan** [comment]
Closing this one. API tests for `CheckFileInfo` will be done in https://github.com/owncloud/ocis/issues/9844
