### ISSUE TITLE
[QA] Left menu elements picks browser's language instead of the oC account settings

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#884]
Tested using oCIS 1.0.0.-RC5

Left menu elements picks browser's language instead of the oC account settings

![Screenshot 2020-11-18 at 11 27 00](https://user-images.githubusercontent.com/10596560/99519504-42589e00-2992-11eb-9c61-505dbd82950d.png)

![Screenshot 2020-11-18 at 11 26 24](https://user-images.githubusercontent.com/10596560/99519537-497fac00-2992-11eb-9116-3ae13ca062d3.png)

**Comment by jnweiger** [comment]
## Retested with rc6
System language: German, 
Einsteins selected language: French

![image](https://user-images.githubusercontent.com/1108546/100771738-119b4e80-33ff-11eb-85e3-27d63886297a.png)

We see a mixture of one third German, one third English and one third French.

Expected behaviour: Tutes francais!
