### ISSUE TITLE
[Sharing NG] Add remix icon to share roles

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#8844]
# Description

Add icons for roles in the `themes.json` in the `common` section.

We add key>value pairs of name->path/to/icon.svg

The icons are basically strings representing an icon from https://remixicon.com/.

* All viewer roles: `eye`
* All editor roles: `pencil`
* Space manager role: `user-star`
* Secure view role: `shield-fill`

cc @micbar @rhafer

**Comment by fschade** [comment]
Done statically in the theme json, no server is involved

**Comment by kulmann** [comment]
> Done statically in the theme json, no server is involved 

Why did you go with the theme.json instead of returning the iconnames from the server? Please document the reasoning here.

Solution seems to be suboptimal to me. We have customers with a custom theme. They will need to adapt thir theme with the next release, which doesn't feel right.

**Comment by fschade** [comment]
since the icon is something visually we’ve decided to ship that via the theme.json. 

Currently a manual change is needed, we also discussed if the server should take care of injecting the icons there, for the moment we’ve decided to not do that. But I’m absolutely fine implementing such a thing (theme pre processing). 

Let me know what you think, even if we decide to have something else, in my opinion it’s great to give the user the ability to have it in the theme since it’s for me the single source of truth for everything that’s visually

**Comment by kulmann** [comment]
As long as we don't support exchanging the entire icon set (I don't see that coming!) it's fine for the server to return the icon names. That's by far the simplest solution I can think of. Having a path in the theme even contradicts the way web currently loads its icons (which is.... by name, not by path).

I don't have a current status on the cross client compatibility (i.e. are the remixicons available in all clients). IMO that should be the case but I doubt that we followed through with it.

What you describe sounds like a cool thing to have in the future (theme preprocessing makes a **lot** of sense) but theming is not our current product focus so for what we currently have it sounds overengineered. 🙈

**Comment by fschade** [comment]
Let’s revisit that topic tomorrow after the standup, I’m sure we find a way to make it wow 🤩

**Comment by kulmann** [comment]
Please note: https://github.com/owncloud/web/pull/10801#issuecomment-2068588941

**Comment by fschade** [comment]
we decided to add a follow up issue which adds a theme processor and ensures defaults.
closed
