### ISSUE TITLE
Research: CephFS in CI - 3 PD

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#8857]
# Description

- Check if the existing ceph/daemon service in  reva could also be used to mount CephFS
- If not, what could be an alternative

**Comment by dragonchaser** [comment]
current experiments are running here: https://github.com/owncloud/ocis/pull/8895

**Comment by dragonchaser** [comment]
POC in #8895  works only either on a privileged docker-container (which is not acceptable from a security point of view), on a static agent which can mount cephfs (same security issue as with the docker-container) or mount a "real" ceph cluster which is wiped daily directly to the underlying hypervisor and pass it as a volume to the pipeline (which has no IMHO real benefit, because the container will just see a posix mount, which is indifferent from a local folder or an nfs volume that is passed there the same way, it would maybe show us some weird side-effects which we need tot tackle in the product)

**Comment by dragonchaser** [comment]
Possible approach to cover some basic tests with ceph: 
- we set up a real ceph cluster
- every drone agent mounts a cephfs from that cluster to `/ceph`
- that folder is passed to every pipeline step that needs it as a volume
- every build creates a subfolder in that volume resulting in a `/ceph/drone/build-23232323`  on the cluster and uses that exclusively
-  as soon as the pipeline has passed a cron-job will clean up the ceph-cluster

**Comment by dragonchaser** [comment]
@micbar I consider this done from a research perspective. Can I close this for now and we discuss further steps in our planning?

**Comment by rhafer** [comment]
> POC in #8895 works only either on a privileged docker-container (which is not acceptable from a security point of view), on a static agent which can mount cephfs (same security issue as with the docker-container) or mount a "real" ceph cluster which is wiped daily directly to the underlying hypervisor and pass it as a volume to the pipeline (which has no IMHO real benefit, because the container will just see a posix mount, which is indifferent from a local folder or an nfs volume that is passed there the same way, it would maybe show us some weird side-effects which we need tot tackle in the product)

Is that exactly the thing we want to cover with this? Testing against a "real" cephfs, like it would appear in production environments to uncover weird side-effects. (This is exactly the stuff that was missing when we first tried NFS in production ...)
