### ISSUE TITLE
[ocis] No SSE event to create odt file 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#8950]
Version	5.1.0-prealpha+9c51bfe98
Web client version	9.0.0-alpha.5

ocis started using docker-compose https://github.com/owncloud/web/blob/master/docker-compose.yml

Steps: 
- `admin` creates space and adds `einstein` to the space
- `einstein` opens space and wait
- `admin` creates new `.odt` file inside of the space

Expected: `einstein` see `.odt` file without reload the page
Actual: no file

https://github.com/owncloud/ocis/assets/84779829/4445d778-bde0-4016-9154-a5299f0b4d29

@kobergj @AlexAndBear I guess it's backend issue? if I'm wrong please move it to web repo

**Comment by AlexAndBear** [comment]
I guess this is a backend issue file-Touch event should fire

**Comment by ScharfViktor** [comment]
a couple more questions about SSE: 


1. a set of events such as editing the contents of a file, copying a file, etc. are called as `postprocessing-finished` . is it okay?
<img width="929" alt="Screenshot 2024-04-24 at 14 20 43" src="https://github.com/owncloud/ocis/assets/84779829/e51fe648-99c8-4b0f-9b56-eadfcf0adf9f">

2. I see that we have event for changing file content but we missed event for restoring version of the file: 
https://github.com/owncloud/ocis/assets/84779829/87241b38-48c2-4da3-a7b4-bd12a09d4822

**Comment by kobergj** [comment]
I can confirm this is a backend issue. Specifically with wopi and the way it is implemented. In a nutshell the problem is that wopi only initializes the upload, but never finishes it. This works because of a loophole in decomposedfs. I need to check how old and new wopi implementations behave so we can tackle this.

> a set of events such as editing the contents of a file, copying a file, etc. are called as postprocessing-finished . is it okay?

Yes. The server cannot differentiate these actions, they are all the same to it.

> I see that we have event for changing file content but we missed event for restoring version of the file:

Has never been in any ticket. Not sure if this was intentional or just forgotten. @micbar @tbsbdr should we add a sse for "item restored from trashbin"?

**Comment by AlexAndBear** [comment]
For "item restored from trash" we have an event but not for versions. 

Please keep in mind that we don't want to go into full detail yet with SSE and don't need to catch every case.
