### ISSUE TITLE
[QA] Blocked user is not logged out

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#902]
Setup via docker-compose-eos-test.yml from branch fix-yml-for-rc5 on localhost

* login as einstein
* login as moss from another brower session
* visit the accounts page, select einstein and chose 'Block'.
The activated column for einstein shows a red cross. OK.

* wait 10 min. Einstein's browser session is unchanged. BAD.
* as user einstein, try several actions. The system responds to all actions with error messages. Okayish  
![image](https://user-images.githubusercontent.com/1108546/99710268-a2d60100-2aa0-11eb-99b8-0d4ee850a016.png)

* but even after such server intraction the user is not logged out. BAD
* a manual logout works.

* a desktop client is logged out after ca 1 min.
  (but has its own issues then: https://github.com/owncloud/client/issues/8241)

### Expected behaviour (according to https://github.com/owncloud/enterprise/issues/4088):
The browser session is eventually logged out.
e.g. forwarded to same access-denied-page as when he tries to log in while blocked:
![image](https://user-images.githubusercontent.com/1108546/99710038-5be80b80-2aa0-11eb-8fa9-48502e90d2de.png)

**Comment by jnweiger** [comment]
Same for a deleted user

**Comment by jnweiger** [comment]
Reproduced with ocis master 2020-12-11 13:30h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

Even worse: https://github.com/owncloud/ocis/issues/1072 [QA] Deleted user can upload files

**Comment by individual-it** [comment]
- [ ] ToDo QA-team: add UI tests for this scenario

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0 and web 4.1.0

Work correct. After 10 minutes of waiting (token still active. But all request are 401) the message "Login Error" displays.  

tests/acceptance/features/webUILogin/adminBlocksUser.feature:13 doest work because we wait element `'//span[@data-msgid="Login Error"]'` but we see at first:
![image](https://user-images.githubusercontent.com/84779829/132196216-663c839f-e1e2-4cb9-a5a1-6ad8143dbeab.png)

**Comment by ScharfViktor** [comment]
needed fix test an

**Comment by fschade** [comment]
Please open again if the ticket is still relevant
