### ISSUE TITLE
[Bug] wopi in web development setup is broken because of CSP

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9084]

**Comment by dschmidt** [comment]
I assume https://github.com/owncloud/ocis/pull/8777 (see also https://github.com/owncloud/ocis/pull/9007) broke it. When using Web on port 9200 directly, icons for opening files with wopi apps are not shown and neither onlyoffice nor collabora load because of CSP. Can you please help us fix the setup, @DeepDiver1975?

**Comment by DeepDiver1975** [comment]
Let me have a look into my crystal call .....

**Comment by dschmidt** [comment]
We're in oCIS Zoom - feel free to join and we'll show you. 

Otherwise: it's just `docker-compose up -d` in the web repo and then browsing to https://host.docker.internal:9200 and trying to use wopi

**Comment by DeepDiver1975** [comment]
> We're in oCIS Zoom - feel free to join and we'll show you.

Not today .... meetings .... :shrug:

**Comment by DeepDiver1975** [comment]
Feel free to look into 
https://github.com/owncloud/ocis/blob/045d5450f0f940e838762112a0331ec2f4c996af/deployments/examples/ocis_wopi/docker-compose.yml#L96
https://github.com/owncloud/ocis/blob/045d5450f0f940e838762112a0331ec2f4c996af/deployments/examples/ocis_wopi/config/ocis/csp.yaml#L16

**Comment by ScharfViktor** [comment]
fix here https://github.com/owncloud/web/pull/10885
