### ISSUE TITLE
Remove `admin_password` from ocis.yaml post changing the password

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#9093]
In the current way, the ocis admin password stays in the `ocis.yaml` file post changing the password.

When running `ocis init`, the pwd is first time set and written to `ocis.yaml` in the `idm:` section. Post changing it either via webUI or command line, the entry is no longer valid.

This is confusing though one can guess changing the pwd in `ocis.yaml` may change it or it is the valid current one.

**Suggestion:** 
Whenever an admin password is changed, independent if via the webUI or the command line, the entry `admin_password` is removed from the `ocis.yaml` file in section `idm:`

@micbar @ScharfViktor @rhafer

**Comment by micbar** [comment]
Interesting idea. But we have other prios now. Default idm is not our first prio. Writing a yaml file is also not straightforward.

from my PoV this is cosmetical.

**Comment by wkloucek** [comment]
oCIS should always consider configuration as read only. This applies naturally to environment variables. But probably also to configuration files, since in most moderate to higly restricted environments, config files will be provided to oCIS as read only anyways (hopefully!!!, at least in Kubernetes this is best practice)
