### ISSUE TITLE
Local storage still used for data with S3ng driver

### ISSUE THREAD

**Issue by ishioni** [owncloud/ocis#9281]
## Describe the bug
When migrating data from nextcloud i initiated an upload of around 20GB of data to ocis. I've set aside around 5GB of drive space for ocis itself because the data would be stored in S3. However around the 5GB mark I've gotten alerts that /var/lib/ocis is full. It seems that ocis first downloads all the data to it's local storage and then once it's done, starts to push it to S3 instead of doing it immediately.

## Steps to reproduce
1. Set a quota for /var/lib/ocis
2. Upload more data than the quota
3.

## Expected behavior
Data gets sent to S3 immiediately

## Actual behavior
Data gets downloaded to local storage and then sent

## Setup
[Relevant config](https://github.com/ishioni/homelab-ops/blob/master/kubernetes/talos/apps/selfhosted/ocis/app/helmrelease.yaml)
S3 is handled by minio on a 10G connection

**Comment by micbar** [comment]
@ishioni 
Your observation is correct.

Ocis uses a local storage for TUS resumable uploads. This makes the uploads very fast.

We tried to send them directly to S3 but that had a big impact on the upload speed.

I doubt that nextcloud handles that differently. Normally a PHP application uses /tmp to temporarily store the uploads.

**Comment by ishioni** [comment]
I actually didn't do any benchmarking to compare the two. However if you could clear up something - does the S3 upload start immediately or does it wait until the client is done uploading?

The limiting factor here is that I don't actually want to give ocis a lot of local storage, yet I am forced to anticipate a maximum upload that it can handle

**Comment by micbar** [comment]
> I actually didn't do any benchmarking to compare the two. However if you could clear up something - does the S3 upload start immediately or does it wait until the client is done uploading?

TUS is designed in a way that it uploads chunks, the upload can be paused and resumed. This enhances the stability of the upload process itself. Once the client has uploaded the last chunk = all bytes has been received by the server, the client gets a `200 OK` and shows that the upload is finished. The file itself shows in the folder with status `425 - Too Early` while the chunks are being assebled, optionally scanned for viruses and then uploaded to the S3 bucket.

> The limiting factor here is that I don't actually want to give ocis a lot of local storage, yet I am forced to anticipate a maximum upload that it can handle

Let me say, everything has its tradeoff 😅 . Having resumable uploads brings a lot of end user value, but also some painpoints for the sysadmin because of the upload storage area. Be aware that there can be a magnitude of GB used for unfinished uploads. We have a cli command which can be used to clean up unfinished uploads. https://doc.owncloud.com/ocis/5.0/deployment/services/s-list/storage-users.html#manage-unfinished-uploads


> I just did the test in reverse - dumped all my data into nextcloud, it's PV is much smaller than the whole amount, yet it never filled up the disk. So either they're faster uploading in some way or they never use the disk space at all (it has mem limit so I doubt it uses /tmp in any meaningful way)

Like I said, we tried to stream to S3 directly, was too slow for our requirements.

**Comment by micbar** [comment]
Closing. Seems that the questions were answered.
