### ISSUE TITLE
 Duplicated sidebar entries on the Phoenix UI

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#930]
![](https://i.imgur.com/D77Ooo7.gif)

(The issue also impacts the number of network requests made from Phoenix)

This issue does not occur with `owncloud/ocis:1.0.0-beta8`

**Comment by kulmann** [comment]
Saw this happening before, when there was an error page after the login. Might be that the app is initialized twice in that case. Needs investigation.

**Comment by butonic** [comment]
@kulmann like this: https://github.com/owncloud/ocis/issues/932

**Comment by kulmann** [comment]
> @kulmann like this: #932 ?

@butonic yes, that's exactly what I meant.

**Comment by IljaN** [comment]
AFAIR we saw this in the bridge setup with a wrong "unauthenticated-policy". Bridge is not involved here right?

**Comment by kulmann** [comment]
The issue was that in case of failing to load an extension, we were re-triggering loading all extensions, just without the failing one. The problem with this is, that the already successfully loaded extensions are loaded again then. While this is not an issue with the vuex store, it was re-adding all routes of the extensions, causing duplicate routes.

As a quick win we introduced that you can now define a default extension in the config.json by setting `options.defaultExtension`. It defaults to the files extension. The first route of the extension will be picked as home route.

**Comment by butonic** [comment]
fix landed in ocis with https://github.com/owncloud/ocis/pull/943

**Comment by kulmann** [comment]
Closing again. Reopening happened by accident.
