### ISSUE TITLE
Add email notification templates to the docker-compose build.

### ISSUE THREAD

**Issue by if0else9** [owncloud/ocis#9306]
Add email notification templates to the docker-compose build.

**Comment by micbar** [comment]
I would not prefer to add these to our example deployments because they should be "as easy as possible".

Customizing E-Mail templates is something for more technical admins. They should know how to mount a volume in docker compose.

The docs about custom templates can be found [here](https://doc.owncloud.com/ocis/5.0/deployment/services/s-list/notifications.html#email-notification-templates).
