### ISSUE TITLE
OCM. search for federated users doesn't contain ocis instance info

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#9813]
related: 
https://github.com/owncloud/ocis/pull/9788
https://github.com/owncloud/ocis/issues/9702
https://github.com/owncloud/ocis/issues/9735

Steps: 
```
Given using server "LOCAL"
And "Alice" has created the federation share invitation
And using server "REMOTE"
And "Brian" has accepted invitation
When user "Brian" searches for federated user "ali" using Graph API
```

Actual: response doesn't contain info about ocis instance (no identities section). 
<img width="1129" alt="Screenshot 2024-08-14 at 16 47 51" src="https://github.com/user-attachments/assets/ce4d0b3f-3516-48df-b502-e13be12e93ad">

Expected: response contains identities section to understand which `ocis` instance this user is from. 
```
"identities": [
                {
                    "issuer": "federation-ocis-server",
                    "issuerAssignedId": "b49ed57c-c562-4740-a5be-4ebc8b947100"
                }
            ]
```

This can be useful if we will be sharing more than 2 `ocis` instances to separate users (this can be in case of same names)

CC @rhafer @tbsbdr

**Comment by phil-davis** [comment]
Yes, there will need to be some way to present a UI so that a user can distinguish which federated instance each user comes from. The API response probably needs to have a federated domain name (or something similar), and then someone needs to think about how best to present something in client UIs that will be user-friendly.
